### ISSUE TITLE
Switch from bigText to toggle image

### ISSUE THREAD

**Issue by DewGew** [EdddieN/machinon-domoticz_theme#10]
When using diffrent language this does not always work.
I found this function in custom.js. The funktion checks status from bigText. And that is already translated.
```
let bigText = $(this).find('#bigtext');
let status = bigText.text();
```
![switch_swedish](https://user-images.githubusercontent.com/28799807/42863734-595bf91e-8a64-11e8-9086-3171345439d3.jpg)
![switch_english](https://user-images.githubusercontent.com/28799807/42863735-597be364-8a64-11e8-9e2c-2e55b269a208.jpg)

**Comment by EdddieN** [comment]
Ok, no idea how to fix this... I only designed the them. If you don't know I can ask my friend who helped me to make making the first alpha version of it

**Comment by DewGew** [comment]
Need to figure out get the status out before translation

**Comment by landaisbenj** [comment]
Maybe bypass by json  ?  In custom.js i think i understoud this can get status of an scene device:
`if (settings.url.startsWith('json.htm?type=command&param=switchscene')) {
				let id = settings.url.split('&')[2];
				id = id.substr(4); // from string 'idx=?'
				let scene = $('.item#' + id);
				let statusElem = scene.find('#status .wrapper');
				statusElem.hide();
				let switcher = statusElem.parent().siblings('.switch').find('input');
				if (switcher.length) {
					let statusText = settings.url.split('&')[3];
					statusText = statusText.substr(10); // from string 'switchcmd=?'
					switcher.attr('checked', (statusText == 'On'));`

Maybe we can modify code to get json value who always not translate.
If not, we must find how to get data-status before it's translate, and for this device in html code...

**Comment by landaisbenj** [comment]
Hm no, it's to create json answer.

**Comment by EdddieN** [comment]
Sorry, is this fixed? I think it is, the only place I see it in on status indicator where the user cannot switch on or off. If fixed (I think it is), can we close?
![screen shot 2018-08-28 at 21 55 59](https://user-images.githubusercontent.com/39434245/44750458-568ff680-ab0d-11e8-93b2-75b67edbb7af.png)

**Comment by landaisbenj** [comment]
I think it's not fixed. Problem is the switch catch the name of bigtext ("on, off, closed, open...") to detect when it must appear. But when the bigtext is translate (in our case, status of bigtext was also translate after get in html code) your switch can not detect the status who known. In my case my blinds not open but ouvert. So the switch don't appear... today i have tried to know how make bigtext translate after apply switch. I can get the status but I can't translate it...

**Comment by DewGew** [comment]
There is a workaround in custom.js, (I have prepared for some kind of translation).
change this code to match your language:
```
switchState = {
	on: 'On', // on: 'På',
	off: 'Off', // off: 'Av',
	open: 'Open', // open: 'Öppen',
	closed:'Closed' // closed: 'Stängd'
}
```
For swedish:
```
switchState = {
        on: 'På',
	off: 'Av',
	open: 'Öppen',
	closed: 'Stängd'
}
```
For french:
```
switchState = {
        on: 'On',
	off: 'Off',
	open: 'Ouvert',
	closed: 'Fermé'
}
```

**Comment by landaisbenj** [comment]
Can't we use i18n?
