### ISSUE TITLE
More depth shadow

### ISSUE THREAD

**Issue by EdddieN** [EdddieN/machinon-domoticz_theme#102]
See attached, we need a bit more. Because the design is very minimalist, we need to add a bit of 3D effect. I think just a tiny bit more shadow will bring the right depth. Or may it is me that I have tired eyes :D 

![screen shot 2018-09-14 at 17 27 20](https://user-images.githubusercontent.com/39434245/45563072-21d9aa00-b844-11e8-9d7f-aee6a2e621ac.png)

**Comment by DewGew** [comment]
@EdddieN Check lastest master

**Comment by EdddieN** [comment]
I know I can be a bit of a pain with details but really like it now. It has much more depth - thanks a lot of fixing! :)
