### ISSUE TITLE
Chart colours

### ISSUE THREAD

**Issue by EdddieN** [EdddieN/machinon-domoticz_theme#108]
Can the colours of the charts be changed to match as below? They don't play very nice together as they are now. 
![screen shot 2018-09-19 at 22 05 38](https://user-images.githubusercontent.com/39434245/45782359-918fd080-bc5a-11e8-8f93-6d829abdd089.png)

The fill option, don't think it is possible, probably part of the domoticz core. Not critical in my opinion, just nice.

**Comment by EdddieN** [comment]
Attached also the chart for energy with wrong font. Zeplin has the right ones
![screenshot 2018-10-19 at 20 31 58](https://user-images.githubusercontent.com/39434245/47239895-7db4c700-d3de-11e8-8c3d-5bea63229557.png)

**Comment by DewGew** [comment]
> Attached also the chart for energy with wrong font. Zeplin has the right ones
> ![screenshot 2018-10-19 at 20 31 58](https://user-images.githubusercontent.com/39434245/47239895-7db4c700-d3de-11e8-8c3d-5bea63229557.png)

Fixed in latest Beta..

**Comment by EdddieN** [comment]
Happy to close?

**Comment by davidlb** [comment]
Yeah, we can close it :)
