### ISSUE TITLE
Offline and Login screens not updated

### ISSUE THREAD

**Issue by EdddieN** [EdddieN/machinon-domoticz_theme#112]
See zeplin, screens for login and offline still show the default theme.
Ignore the machinon logo in zeplin, my preference would be either user custom text or even logo if possible to do from within the Theme settings?

**Comment by landaisbenj** [comment]
For Login page first try. Not finished.
```

#login.ng-scope:before  {
	display:none;
}
#login.ng-scope {
	border: none;
	background: white;
	padding:0;
	width:450px;
	height: auto;
}
#login h1:after, #login h1:before {
    content: none !important;
}
#login h1 {
	background: linear-gradient(to right, #0bcdc7 0%, var(--main-blue-color) 100%);
	height: 70px;
margin-bottom: 20px !important;
}

#login #inputs input[type=text], #login #inputs input[type=password]  {
    border: none;
    border-bottom: 1px solid #ccc;
    border-radius: 0;
    -moz-border-radius: none !important;
    -webkit-border-radius: none !important;
    border-radius: none !important;
    -moz-box-shadow: none !important;
    -webkit-box-shadow: none !important;
    box-shadow: none !important;
}

#login fieldset {
	text-align: center;
    padding: 0px!important;
    padding-bottom: 20px!important;
    margin: auto !important;
    width: 25%;
}
#login #actions a {
    display: none;
}


#inputs .input {
    background: #fff url(images/login-sprite.png) no-repeat;
}
```

**Comment by DewGew** [comment]
Try it in beta branch

**Comment by landaisbenj** [comment]
Yes. Need to finish first

**Comment by landaisbenj** [comment]
Ok i think i've done for login page

**Comment by EdddieN** [comment]
Is there a way to load the beta tree similarly to git clone https://github.com/EdddieN/machinon-domoticz_theme.git machinon as a new theme?

**Comment by landaisbenj** [comment]
Maybe this ? 

> git clone -b beta https://github.com/EdddieN/machinon-domoticz_theme.git machinon

Need to try...

**Comment by EdddieN** [comment]
I did this, so I can test both stable and beta:

cd domoticz/www/styles
git clone https://github.com/EdddieN/machinon-domoticz_theme.git machinon-beta
cd machinon-beta
git checkout beta

**Comment by EdddieN** [comment]
Ah! and the login works great!

However the offline it just shows a blank screen (black)

**Comment by landaisbenj** [comment]
Yes good idea!!! I must do the same. 

For offline screen I don't know how to see change xD

**Comment by landaisbenj** [comment]
A yes maybe with domoticz stop !!!

**Comment by EdddieN** [comment]
Yes, that is what I tried, to stop domoticz and this is when I saw the black screen but not sure if it was because it could not load or was actually offline.... no idea how to force it

**Comment by DewGew** [comment]
Is the offline page fixed?

**Comment by landaisbenj** [comment]
Not for the moment.

**Comment by landaisbenj** [comment]
It tought this change:
```
body{
  background:#f1f1f1 !important;
}

#offline h3:after, #offline h3:before,#offline:after, #offline:before  {
    display:none;
}
#offline{
    content: url(../images/logo.png) !important;
    background: linear-gradient(to right, #0bcdc7 0%, var(--main-blue-color) 100%);
}
```

But appear no work... I think is in html style...
