### ISSUE TITLE
Dark theme small charts fix

### ISSUE THREAD

**Issue by EdddieN** [EdddieN/machinon-domoticz_theme#114]
Charts tittle on dark theme is black, replace to white?

Background charts are white, replace to grey/black?

I'm aware the design of dark theme has not been done, just suggesting so it is less eye-sore on those things in the  meantime :D

Also, for whatever reason the chart does not appear centered (white or dark theme)

![img_0114](https://user-images.githubusercontent.com/39434245/45782936-48d91700-bc5c-11e8-856c-6d20ed45f937.jpg)

**Comment by landaisbenj** [comment]
Need zeplin

**Comment by EdddieN** [comment]
What do you think?
![temperature and humidity dark](https://user-images.githubusercontent.com/39434245/47667614-57411980-db9e-11e8-8625-0d16438f7fda.png)

**Comment by DewGew** [comment]
Looks great

**Comment by DewGew** [comment]
Background color fixed in beta..

**Comment by EdddieN** [comment]
thanks, you did it faster than I had a chance to upload to Zeplin! 😄

**Comment by DewGew** [comment]
:) only 1 line to change...hard work ...
