### ISSUE TITLE
some new icons to be added

### ISSUE THREAD

**Issue by EdddieN** [EdddieN/machinon-domoticz_theme#117]
Here are some new icons I think are missing and I'm not sure where to put them on Domoticz

I tried the switch text file inside the www but no luck
[icons.zip](https://github.com/EdddieN/machinon-domoticz_theme/files/2420729/icons.zip)

**Comment by landaisbenj** [comment]
Icons added on /images. without meter.pdf and all on mac os folder. We need .png file. And i don't succed to open all file on macos folder on my desktop.

**Comment by landaisbenj** [comment]
For the moment to use icon, we need to follow the step on: https://www.domoticz.com/wiki/Custom_icons_for_webinterface#Editing_icon_description_file

**Comment by landaisbenj** [comment]
Maybe in futur we can make other thing on theme.

**Comment by EdddieN** [comment]
You mean to add them as per default? That is what I was hoping, instead of using the user icon upload via the GUI

Did you manage to add them? I can try to it from windows computer to remove mac stuff

**Comment by landaisbenj** [comment]
We need to make custom icon more easy. But not now. I don't have much time :( so I'm focus on tile, js detect and reorganize code.

**Comment by DewGew** [comment]
I think the icon is implemeted in the database. Only way to add them is via custom icons uploader.

**Comment by EdddieN** [comment]
mmm... and this one does not work too well...
http://domoticz-icon.aurelien-loyer.fr/ wonder if it could be integrated as part of the toolset of Domoticz
