### ISSUE TITLE
Tiles different sizes in Firefox than Safari/Chrome

### ISSUE THREAD

**Issue by EdddieN** [EdddieN/machinon-domoticz_theme#118]
See attached, not sure if a visual bug or a feature. 
![screenshot 2018-09-28 at 20 36 27](https://user-images.githubusercontent.com/39434245/46229743-89244d80-c35e-11e8-882e-c05dcd849a9d.png)

**Comment by landaisbenj** [comment]
I think i've don't apply moz or other webkit on flex. But at this time I try to make tile more spaci with flex. I think I can solve this too.

**Comment by EdddieN** [comment]
Ok, for me is not a big thing to be honest. I’ll leave it open and assign to you. Feel free to close when you get tired of seeing it.

**Comment by landaisbenj** [comment]
Nop I'm on it to Firefox and to restructur all tile and object on tile. Let me some week.

**Comment by landaisbenj** [comment]
may fix after many change with #31.

**Comment by EdddieN** [comment]
I actually like a bit of breezing space between tiles. For a small screen like a mobile, then the "Firefox" view is ok, but for a big desktop one, I'm happy with the "Safari" view

**Comment by landaisbenj** [comment]
Like other it's flex bug. Flex box on safari don't run like other. I need to make a great tile, static and visually breathily and after that make margin flexibly. But I need to understand how I can make this for all screen.

**Comment by EdddieN** [comment]
I'm not a coder but happy to have a look. What is flex? Maybe the solution is to tell the browser, 3 or 4 options and that is it. No progressive detect, only if >10 = 1 tile, >2 = 2 tiles... 
I know I'm oversimplifying :D - I did say I was no coder!

**Comment by landaisbenj** [comment]
Make this mean work with table like. Maybe more easy but flex is propriety who do this alone and responsibly. But all item must be configured with good width parameter...

Domoticz work with table. Who make just one option: 3 tile by row. It's bootstrap rule. Maybe we can change that but all other item (group btn, img, bigtext and other) are configured with just this rules.. flex can adapt all other item with tile on resize windows... but for this we must do a good start.

**Comment by EdddieN** [comment]
I see! ok, sounds very complex. I better standby and let the experts (you)  ;)

**Comment by landaisbenj** [comment]
Just need little time to organise custom.css, banner, container, tile and item with media screen. 

Today I've start to organize custom.css to separate all item on all tile (dashcontent, weathercontent etc...)

**Comment by EdddieN** [comment]
tiles are now the same everywhere (Safari, Chrome and Firefox) on beta. Closing.
