### ISSUE TITLE
 The small icon for the logpage link is missing on the tiles at the temperatures tab

### ISSUE THREAD

**Issue by rwaaren** [EdddieN/machinon-domoticz_theme#119]
Machinon theme V.1.3.1
domoticz version V4.10032
Debian stretch on RPI-3

The small icon on the Scenes, Utilities, Switches and Weather sensor tabs to link to the logpage are not in use for temperatures.
Please see png on [http://www.domoticz.com/forum/viewtopic.php?f=8&t=24084&start=320]

**Comment by DewGew** [comment]
Try machinon beta branch..

**Comment by rwaaren** [comment]
I tested on Chrome, Firefox and Edge all on Windows 10 Both on my desktop as on my laptop.
I am using domoticz V4.10032 / Machinon theme V.1.3.1
Just did a:
git pull
copied templates/Settings.html to www/templates
restarted domoticz
cleared cache (including images) and appcache 
reset the theme when asked
No difference

**Comment by rwaaren** [comment]
as posted on domoticz forum:
Still no Fun on V4.10038 with stable or beta theme.
Installed V4.9700 (aka stable) on my test system together with beta machinon and there they are !!
I know gizmocuz is working on log related stuff so maybe related ?

**Comment by DewGew** [comment]
Something changed in latest domoticz beta version..

**Comment by EdddieN** [comment]
Do we leave this open... or close? I think we should work only on stable release, otherwise beta + beta = alpha :D

**Comment by rwaaren** [comment]
Nice math :-)
I have no real preference but do think that many (most ?) users who switched to machinon theme are on the forum and using domoticz beta. Moreover because domoticz stable is certainly not bugfree and bugs are not fixed in domoticz stable.

**Comment by EdddieN** [comment]
Hehe! I haven’t got any bug on stable, but maybe is because I’m not using it to its full potential. 
Ok, let’s leave it open then but it is.going to be a lot harder to chase to moving parts than just one. 
I will try the beta version (Domoticz) see where I get. 
I’ll update the status of this issue too

**Comment by sweetpants** [comment]
Implemented #131 locally and can confirm it works
