### ISSUE TITLE
Theme settings fail to load behind proxy

### ISSUE THREAD

**Issue by EdddieN** [EdddieN/machinon-domoticz_theme#126]
If loading web gui behind proxy, it fails to load the settings page, probably issue with absolute path

**Comment by DewGew** [comment]
In master or beta?

**Comment by EdddieN** [comment]
I think beta, I have assigned this to @mattlogic as he is the one who mentioned it. He found the extra "../" that caused the problem, maybe he can commit

**Comment by mattlogic** [comment]
Hmm, I've already committed my path changes in the beta branch (not master) and it's working for me when I browse to the settings page with direct local access (\<ip\>:8080/#/Custom/Settings), via a local proxy (\<ip\>:80/domoticz/#/Custom/Settings) and via my.domoticz.

Make sure you are on the beta branch and have pulled the latest changes...
```
cd domoticz/www/styles/machinon-beta   (or whatever your theme folder is called)
git checkout beta
git pull
```
Also make sure you have actually copied the settings.html file to domoticz/templates and that it's readable by domoticz (should already be)

 I have master and beta branches checked out into separate theme folders so I can easily switch between them in Domoticz.

**Comment by DewGew** [comment]
I have change this in master.. closing this issue
