### ISSUE TITLE
Do not have option_bars for push on switch :?

### ISSUE THREAD

**Issue by landaisbenj** [EdddieN/machinon-domoticz_theme#13]
![image](https://user-images.githubusercontent.com/32144431/42953779-7163e2ac-8b7b-11e8-9bb6-dfd3a02a471a.png)

**Comment by landaisbenj** [comment]
I don't know if i too much play with css or other lol...
If you create a push on switch light, did you have it ?

**Comment by EdddieN** [comment]
I think is cache, it works for me. I see the blue gear cog ok

**Comment by EdddieN** [comment]
Actually for me is ok, but it is blue. Shouldn't it be green only for a push button?

**Comment by landaisbenj** [comment]
You have Blue gear because it's not pushed... For push button it was 2 icon too. One for none pushed and one for pushed. You don't change this for the moment.
But it's not my real problem... You don't have 3 dot menu too lol

**Comment by EdddieN** [comment]
Ok, I'll close this one then for now
