### ISSUE TITLE
Flex propriety for tile need to be inproved

### ISSUE THREAD

**Issue by landaisbenj** [EdddieN/machinon-domoticz_theme#130]
If we can detect all change in code, we try to add flex propriety on all tile.

But flex may some organize between mobile or desktop screen to work with together. And media screen propriety on custom.css may inteferer with him.

We need to let make flex alone for size off all object and for this, custom.css may be clean.

**Comment by DewGew** [comment]
I saw this also .. its alot now  :) .. no space between tiles..

![space](https://user-images.githubusercontent.com/28799807/46531990-85815100-c89f-11e8-956c-60b161d9e98d.png)

**Comment by EdddieN** [comment]
Yes, here is a transtion of reducing the width of the screen from big to small:
![screenshot 2018-10-05 at 18 03 40](https://user-images.githubusercontent.com/39434245/46549291-613a6a00-c8c9-11e8-8c51-b998ae92cf1f.png)
then smaller
![screenshot 2018-10-05 at 18 03 47](https://user-images.githubusercontent.com/39434245/46549297-67c8e180-c8c9-11e8-8b4c-fb68ac6e3b3c.png)
and even smaller
![screenshot 2018-10-05 at 18 03 55](https://user-images.githubusercontent.com/39434245/46549301-6dbec280-c8c9-11e8-8888-c324419a0395.png)
after this, it goes back to normal

**Comment by landaisbenj** [comment]
I'm it!

**Comment by EdddieN** [comment]
Works really well now! Brilliant work
