### ISSUE TITLE
Stupid begginer  question

### ISSUE THREAD

**Issue by michass** [EdddieN/machinon-domoticz_theme#133]
Hi, how to switch between master and beta? I have master, but i want beta, i try with google to find solution, but don't work.

**Comment by sweetpants** [comment]
cd ~/domoticz/www/styles
git clone https://github.com/EdddieN/machinon-domoticz_theme.git machinon-beta
restart domoticz
select machinon-beta theme in settings

**Comment by DewGew** [comment]
Try this: git clone https://github.com/EdddieN/machinon-domoticz_theme --branch beta machinon-beta

**Comment by michass** [comment]
Don't work 😥

**Comment by michass** [comment]
git clone -b beta  https://github.com/EdddieN/machinon-domoticz_theme.git machinon-beta
I have!
