### ISSUE TITLE
Add idx on tile

### ISSUE THREAD

**Issue by landaisbenj** [EdddieN/machinon-domoticz_theme#135]
Like aurora de must add idx on statut or lastseen.

**Comment by EdddieN** [comment]
Can you paste a screen of what you mean? I'm not sure what you mean, but happy to have a look design wise

**Comment by DewGew** [comment]
Im working on this....

**Comment by landaisbenj** [comment]
> I would be careful not to overwhelm the screen with too much information, it will get confusing for the non expert user. What do you think something like this? click edit and appears in small next to the start (right justified)
> ![screenshot 2018-10-15 at 10 59 11](https://user-images.githubusercontent.com/39434245/46944262-82d5e700-d069-11e8-90d4-ff8ed97bdf02.png)

I think IDX is more important as type... In this: 
![image](https://user-images.githubusercontent.com/32144431/46961025-25a95800-d0a0-11e8-8e76-50ea1b539d1f.png)

i have idx and type. But type isn't needed for dayly use.... maybe just on edit menu is enough...

**Comment by landaisbenj** [comment]
> > I would be careful not to overwhelm the screen with too much information, it will get confusing for the non expert user. What do you think something like this? click edit and appears in small next to the start (right justified)
> > ![screenshot 2018-10-15 at 10 59 11](https://user-images.githubusercontent.com/39434245/46944262-82d5e700-d069-11e8-90d4-ff8ed97bdf02.png)
> 
> I think IDX is more important as type... In this:
> ![image](https://user-images.githubusercontent.com/32144431/46961025-25a95800-d0a0-11e8-8e76-50ea1b539d1f.png)
> 
> i have idx and type. But type isn't needed for dayly use.... maybe just on edit menu is enough...

Like aurora where no type is displayed..

**Comment by EdddieN** [comment]
yes I would agree, that information is not critical and cut sit well under the 3 dot menu (edit)

**Comment by DewGew** [comment]
I tryed this:

![idx](https://user-images.githubusercontent.com/28799807/46961290-c1d35f00-d0a0-11e8-8128-fa2772ecaef4.png)

when I click the "Idx: x" it opens devices page

**Comment by landaisbenj** [comment]
Hm. You really think type is more important than idx ?

**Comment by DewGew** [comment]
Idx is used alot in events, great help when writing scripts

**Comment by landaisbenj** [comment]
Yes, so why don't replace type by idx... If you need idx on script, no more easy to view idx on tile than click on 3 dot..
By the way Light/switch, Switch, ON/OFF is really no needed...

**Comment by DewGew** [comment]
Yes, it matter of taste :) but there is no type on temperatures and weathers.

**Comment by landaisbenj** [comment]
damn

**Comment by DewGew** [comment]
We could just add a div and add where we want

**Comment by landaisbenj** [comment]
How?

Benjamin

Envoyé de mon iPhone

Le 15 oct. 2018 à 18:43, DewGew <notifications@github.com<mailto:notifications@github.com>> a écrit :


We could just add a div and add where we want

**Comment by EdddieN** [comment]
Maybe something like this?
![screenshot 2018-10-15 at 20 17 02](https://user-images.githubusercontent.com/39434245/46972870-809a7980-d0b7-11e8-9f5b-9c193885f0a3.png)

**Comment by DewGew** [comment]
> How?
We can place this anywere we want on tiles with javascript

**Comment by landaisbenj** [comment]
Yes but how do you say, "tile appear in html code", so add a div..
Because tile isn't on index, is appear just when "lightcontent" appear. So when javascript be execut ?

Can you show me ?

(i don't know how say that...)

**Comment by DewGew** [comment]
For example with this you can add a  new div in side the div "existingDiv":
`$('<div id="name" class="name"></div>').appendTo('existingDiv');`

**Comment by EdddieN** [comment]
What about if we present it as tooltip? after few seconds it gives you tech info, no need to make it appear on the tile all the time and confuse user?

<img width="380" alt="screenshot 2018-10-16 at 17 46 36" src="https://user-images.githubusercontent.com/39434245/47032931-75a12100-d16b-11e8-96be-fca34506b35e.png">

**Comment by DewGew** [comment]
Good idea..

**Comment by landaisbenj** [comment]
Yes really good thing. Maybe with device type too...

**Comment by DewGew** [comment]
I like it as it is.. I can leave the dropdown down and move the mouse. I can even have several down when i making a script in an other tab or in an editor.

**Comment by EdddieN** [comment]
Ok, can we at least give it less importance to that text? At the moment all option in the menu have the some weight (font, size, colour...) I think the IDX is not for everyday and should be less obvious. Still there but with less weight, for example smaller font and slightly grey?

**Comment by EdddieN** [comment]
is this done? can be closed?

**Comment by DewGew** [comment]
I think its done.
