### ISSUE TITLE
Settings page miss-aligned

### ISSUE THREAD

**Issue by EdddieN** [EdddieN/machinon-domoticz_theme#14]
The setup page is aligned to the left, should not be centre? 
Use a wide screen monitor, you'll see
![screen shot 2018-07-19 at 22 17 35](https://user-images.githubusercontent.com/39434245/42970582-96460f66-8ba1-11e8-8a06-abce4366ee08.png)

**Comment by DewGew** [comment]
It need to be align left because if you have a wider screen, you get 5 columns or you have a smaller size you get 3 columns. 
Resize your window or zoom in and out in chrome you will notice.

**Comment by EdddieN** [comment]
Yes, tested, see attached.  So no option to have it align=centre at all?
![screen shot 2018-07-20 at 08 35 07](https://user-images.githubusercontent.com/39434245/42989547-05a2c3c6-8bf8-11e8-9c35-aa3b2bfb4d3f.png)

**Comment by landaisbenj** [comment]
If switch page can be aligned i think this page can be too?

**Comment by landaisbenj** [comment]
An in this way i think text must have left align no ?

**Comment by landaisbenj** [comment]
I have this:

![image](https://user-images.githubusercontent.com/32144431/43008168-95587c94-8c3a-11e8-9feb-5951e45cea83.png)

**Comment by DewGew** [comment]
To long names in french 😉
Bigger rectangle try increase Edith in .rectangle8 in settings.css

**Comment by landaisbenj** [comment]
Lol yes i know :'( xD if i want translate in french: "what is this thing" it' became : 
![image](https://user-images.githubusercontent.com/32144431/43010540-f99ce8a6-8c40-11e8-82bb-59e7a4d7b538.png)

xDxDxD F*ck*n french...

So with 400px it's work. But why don't you make them with flex ?? It's really flowable to use...

**Comment by DewGew** [comment]
Maybe you can try that. Im useless in css..

**Comment by DewGew** [comment]
dropdown-content:hover make it visual

**Comment by landaisbenj** [comment]
do not work.

**Comment by DewGew** [comment]
I user dropdown from here: https://www.w3schools.com/css/css_dropdowns.asp

**Comment by landaisbenj** [comment]
Ok thanks !! it's work. I must to modify html to.

**Comment by landaisbenj** [comment]
You can see now with the last 2 patch. It's pretty cool. I think i can add this stuff on all device for more flowable

**Comment by DewGew** [comment]
Do you have latest with commit #12

**Comment by landaisbenj** [comment]
Lol I think. I have master with got pull so I think so...

**Comment by landaisbenj** [comment]
omg i forgot to copy/paste

**Comment by EdddieN** [comment]
Looks like the latest update has the settings page a bit broken?
![screen shot 2018-07-21 at 20 34 12](https://user-images.githubusercontent.com/39434245/43039456-86f848be-8d25-11e8-8dae-c0be53e70d3a.png)

**Comment by landaisbenj** [comment]
Yes I don't know why. I think I miss one copy past. The last pull request may fix that.

**Comment by EdddieN** [comment]
yes, that fixed it! Thank you! closing this :)
