### ISSUE TITLE
Info bull issue

### ISSUE THREAD

**Issue by landaisbenj** [EdddieN/machinon-domoticz_theme#144]
![image](https://user-images.githubusercontent.com/32144431/47010882-9c962d80-d140-11e8-88c8-998285c99b2c.png)

Info isn't the right thing

**Comment by DewGew** [comment]
whats this??

**Comment by landaisbenj** [comment]
google trad "tooltip"

**Comment by EdddieN** [comment]
Sorry mixing things he, just wondering if the tooltip would be a good idea for the IDX and type of switch, that way no need to tap on anything. Just over a few seconds over it and it gives you the tech data?

**Comment by EdddieN** [comment]
Not sure what is this, sounds related to the IDX https://github.com/EdddieN/machinon-domoticz_theme/issues/135 

Closing and we follow on the other issue.

**Comment by landaisbenj** [comment]
No. If my mouse hover switch, tooltip display on but it's off...

**Comment by EdddieN** [comment]
Oh yes, I see what you mean...
![screenshot 2018-10-19 at 20 36 17](https://user-images.githubusercontent.com/39434245/47239958-b2288300-d3de-11e8-8c38-7126e1f31f03.png)

**Comment by landaisbenj** [comment]
👍🏻

**Comment by landaisbenj** [comment]
This is it :
![image](https://user-images.githubusercontent.com/32144431/47416912-0af97200-d777-11e8-9e2e-22f644e1fb38.png)
think here:
https://github.com/EdddieN/machinon-domoticz_theme/blob/fff54ae40f15d6779e9ce784137fd792f4ab75de/js/functions.js#L116

And i don't know what is this ?_?
https://github.com/EdddieN/machinon-domoticz_theme/blob/fff54ae40f15d6779e9ce784137fd792f4ab75de/js/functions.js#L117

**Comment by DewGew** [comment]
Fixed in latest beta..
