### ISSUE TITLE
Notifications request

### ISSUE THREAD

**Issue by DewGew** [EdddieN/machinon-domoticz_theme#146]
I updated lastest beta with some improvment on notfications. Now we can clear list and I added some new notifications:
![dashboard](https://user-images.githubusercontent.com/28799807/47147624-f167ae80-d2ce-11e8-9347-ed028f1197f1.png)

@EdddieN @landaisbenj 

Give us suggestion for more notifications

**Comment by EdddieN** [comment]
Great, can the domoticz update itself be put there too? or do we have 2 sets of notifications?

**Comment by EdddieN** [comment]
Maybe worth putting a post on the forum. Also it would be nice to find out a why to tell if domoticz had a re-start while no one was looking or things like that.

**Comment by DewGew** [comment]
Now domoticz update notification is integrated.. :)

**Comment by EdddieN** [comment]
yeehaaa! 😎
