### ISSUE TITLE
Button slider speed

### ISSUE THREAD

**Issue by EdddieN** [EdddieN/machinon-domoticz_theme#15]
Not sure if an issue, when I click on a switch, it takes about 1 second for the blue slider to move. 

Does this happen to you?

**Comment by landaisbenj** [comment]
Yes i think it's in it's js code.

**Comment by EdddieN** [comment]
Can it be improved or is it just JS limitation?

**Comment by EdddieN** [comment]
I also think we should move from this design that gets a bit cramped on tablets:
![screen shot 2018-08-07 at 12 55 43](https://user-images.githubusercontent.com/39434245/43774545-58d6d0f8-9a41-11e8-8f4a-19355af86ce5.png)
the slider button with the menu
to this design that has more breezing space:
![screen shot 2018-08-07 at 12 56 13](https://user-images.githubusercontent.com/39434245/43774560-6873e960-9a41-11e8-969e-b6170603bdf7.png)
all in zeplin

**Comment by landaisbenj** [comment]
I don't know. I think i had saw 400 ms for animation... I don't remember where. I can try to find it.

**Comment by landaisbenj** [comment]
Hm 400ms it's animation of slider. So it's not that.. But i've time also for icon animation.. So i think it's all the site.
