### ISSUE TITLE
Messy Incremental Counters

### ISSUE THREAD

**Issue by sweetpants** [EdddieN/machinon-domoticz_theme#151]
Incremental counters look a little messy because the type occupies two lines instead of one
![image](https://user-images.githubusercontent.com/23421160/47258541-e19dc500-d49c-11e8-8272-99ce30c818f6.png)
Edit: Seems to be in Beta branch only, master branch looks ok
![image](https://user-images.githubusercontent.com/23421160/47258714-6be72880-d49f-11e8-8b99-928188772692.png)

**Comment by landaisbenj** [comment]
What is the display ? Tab ?

**Comment by EdddieN** [comment]
That would be the utility tab

**Comment by EdddieN** [comment]
Mine is ok
![screenshot 2018-10-26 at 20 19 18](https://user-images.githubusercontent.com/39434245/47587943-75b7d280-d95c-11e8-8bbd-478d9b4ba543.png)
