### ISSUE TITLE
interesting and unexpected alignment

### ISSUE THREAD

**Issue by heggink** [EdddieN/machinon-domoticz_theme#152]
After clicking a device on my dash, I got this:

![capture](https://user-images.githubusercontent.com/3987735/47283855-4c5a1800-d5e5-11e8-98fc-757284f6f71a.JPG)

Nice tho less effective IMHO :-).

**Comment by DewGew** [comment]
I can reproduce this issue... are you using machinon theme version 1.4.0?

**Comment by landaisbenj** [comment]
I've reproduce this with small bug on code... Btw i think i can prevent this on replace flex by grid. Maybe next pull.

**Comment by heggink** [comment]
I am indeed on 1.4.0

**Comment by landaisbenj** [comment]
Wich browser ?

**Comment by EdddieN** [comment]
Cannot replicate, can you?

**Comment by DewGew** [comment]
No.. i think it just need a theme reset.
