### ISSUE TITLE
Font: Add local use ?

### ISSUE THREAD

**Issue by DewGew** [EdddieN/machinon-domoticz_theme#153]
After changing font-family to var(main-font) its not wotking for me, 
Before:

![font](https://user-images.githubusercontent.com/28799807/47339400-65bd9b80-d69b-11e8-86d3-c590d3d7aa32.png)

Now:

![font2](https://user-images.githubusercontent.com/28799807/47339407-6e15d680-d69b-11e8-9428-3a2ba13bbaa5.png)

**Comment by DewGew** [comment]
Or Is it just me?

**Comment by DewGew** [comment]
I got an error on all font-family elements 👎 
![fonts](https://user-images.githubusercontent.com/28799807/47341155-96540400-d6a0-11e8-9e25-d66ce2b1e4f9.png)

**Comment by landaisbenj** [comment]
Ok i have to. It's because the font is on style.css too..

**Comment by landaisbenj** [comment]
So this :
```
@font-face {
    font-family: main-font;
    src: url(font/OpenSans-Regular.ttf);
}
@font-face {
    font-family: main-font-bold;
    src: url(font/OpenSans-SemiBold.ttf);
}
```

Is not:
![image](https://user-images.githubusercontent.com/32144431/47342340-c650d680-d6a3-11e8-9f82-9a2c535a5155.png)

**Comment by landaisbenj** [comment]
O maybe it's my work lan !!!
2s i try to put it manually

**Comment by landaisbenj** [comment]
Ok it's because i can't download on cach i think. We can make change. My work lan really sux.
Maybe we can try to use local font... But i don't know how...

**Comment by landaisbenj** [comment]
I make change on master.

**Comment by landaisbenj** [comment]
Don't work too with local use: `font-family: OpenSans-Semibold;`
oO
