### ISSUE TITLE
Right click setup option

### ISSUE THREAD

**Issue by EdddieN** [EdddieN/machinon-domoticz_theme#16]
Is it possible to enable open link on new tab?
![screen shot 2018-07-19 at 22 50 12](https://user-images.githubusercontent.com/39434245/42972098-4c590228-8ba6-11e8-93b3-4c7b48f381e6.png)

**Comment by DewGew** [comment]
How do you mean? it already works like this..

**Comment by EdddieN** [comment]
I think we can close this, it really is a very small thing. 
If anyone really misses it, feel free to re-open.
