### ISSUE TITLE
Alerts New function

### ISSUE THREAD

**Issue by DewGew** [EdddieN/machinon-domoticz_theme#160]
See below.. Im working on a alert or notfication function. Plan is to add sound alerts also. Maybe its overkill with 2 nofications .. :)

![alerts](https://user-images.githubusercontent.com/28799807/47603610-cd068300-d9ee-11e8-97ac-4bedfa1e11b5.png)

Notification alerts fades out after 5 sec.

@EdddieN 
@landaisbenj

**Comment by DewGew** [comment]
You can have both.. this one is for visual alert.

**Comment by EdddieN** [comment]
Cannot be the “chrome cast “ next to the bell alert icon on top banner? Only temporarily for 1 second and disappears?

Having 2 notifications in 2 or 3 places on the screen will get confusing for the non tech, and also a bit overwhelming?

**Comment by EdddieN** [comment]
Like this
![alerts](https://user-images.githubusercontent.com/39434245/47620683-d2de9000-dae4-11e8-9f4a-dc74f3c09c47.jpg)

**Comment by EdddieN** [comment]
In fact I can work on the whole notification popup, I think it could do with a big of high tech electric translucent glow

**Comment by landaisbenj** [comment]
I'm not for too much notification display zone. We need just one. But maybe we need to find a good stuff to screen this. Do you saw notification on aurora?

**Comment by EdddieN** [comment]
Agree, we need to be careful we don’t overdo it.

No I haven’t used Aurora, can you paste a screen?

**Comment by landaisbenj** [comment]
Can do this tomorrow.

**Comment by DewGew** [comment]
New suggestion...

![alerts](https://user-images.githubusercontent.com/28799807/47635708-48cf0f80-db56-11e8-81c4-d09b19efba57.png)

**Comment by landaisbenj** [comment]
I don't know how to make a notification on demand...

**Comment by landaisbenj** [comment]
> New suggestion with a small arrow...
> 
> ![alerts](https://user-images.githubusercontent.com/28799807/47635708-48cf0f80-db56-11e8-81c4-d09b19efba57.png)

Yes, like a drawer.

**Comment by EdddieN** [comment]
What do you think?
![notifications](https://user-images.githubusercontent.com/39434245/47667573-3aa4e180-db9e-11e8-8822-8d63490c7073.png)

**Comment by DewGew** [comment]
In beta I have added some more nofications as, device timed out, low battery. 
Also custom menu work as expected

**Comment by landaisbenj** [comment]
Really good idea!!!

**Comment by EdddieN** [comment]
This is done, right? 
Closing the issue then
