### ISSUE TITLE
Different tiles on each tab

### ISSUE THREAD

**Issue by michass** [EdddieN/machinon-domoticz_theme#161]
Hi,
why on some tabs tiles looks great, on another isn't good?
Desktop tab:
![image](https://user-images.githubusercontent.com/43785139/47635809-9186c880-db56-11e8-824f-3255eb0df216.png)

Switches tab:
![image](https://user-images.githubusercontent.com/43785139/47635833-9ea3b780-db56-11e8-8fef-8163f02c86b5.png)

Temperature tab:
![image](https://user-images.githubusercontent.com/43785139/47635858-b0855a80-db56-11e8-924a-feb9c8c49510.png)

Weather tab:
![image](https://user-images.githubusercontent.com/43785139/47635875-ba0ec280-db56-11e8-8996-06afcd5689c7.png)

Utility tab:
![image](https://user-images.githubusercontent.com/43785139/47635890-c7c44800-db56-11e8-8b1a-ca550d45ccb6.png)

On desktop:
![image](https://user-images.githubusercontent.com/43785139/47636520-dd3a7180-db58-11e8-9d6c-3b668c9d7078.png)

![image](https://user-images.githubusercontent.com/43785139/47636540-f17e6e80-db58-11e8-9bd2-f45ca6c11abb.png)

**Comment by landaisbenj** [comment]
Yes i really need to fix container and item on mobile and desktop...
