### ISSUE TITLE
Swipe tab on mobile view

### ISSUE THREAD

**Issue by michass** [EdddieN/machinon-domoticz_theme#162]
Hi, maybe you can add swipe, to change tab in mobile view :d

**Comment by EdddieN** [comment]
Do you mean scrolling horizontally from tab to tab? Like from Switches to Temperature?

I think that probably needs to be done on Domoticz, besides that may get a bit clunky for big systems. A swipe menu on a web is done in Ajax, right? That would mean pre-load all the tabs in page.... 
No expert on web development though.

**Comment by EdddieN** [comment]
I think is best to merge this here
https://github.com/EdddieN/machinon-domoticz_theme/issues/245 as is very similar.
