### ISSUE TITLE
btn-group

### ISSUE THREAD

**Issue by landaisbenj** [EdddieN/machinon-domoticz_theme#164]
This change, or it's me  ? 

![image](https://user-images.githubusercontent.com/32144431/47802125-f3e6f100-dd2f-11e8-8c31-be66e3c630fa.png)

**Comment by DewGew** [comment]
I haven’t changed this.. I dont use this function at the moment

**Comment by landaisbenj** [comment]
Ok so it's collateral

**Comment by EdddieN** [comment]
Is this a bug or something to do with it?

**Comment by EdddieN** [comment]
can be closed? I haven't seen it

**Comment by DewGew** [comment]
I thinks this is not an issue..
