### ISSUE TITLE
Notifications icon?

### ISSUE THREAD

**Issue by EdddieN** [EdddieN/machinon-domoticz_theme#165]
I just noticed this, I think I know what it is... is it a way to link a change of status to the notification bar?
![screenshot 2018-11-01 at 18 42 12](https://user-images.githubusercontent.com/39434245/47872371-4abefa00-de06-11e8-87f6-f2d0eb221d15.png)
Did not work for me. 

Also, don't think we got the design right if it is the above. Notification menu and notification icon.

Could you clarify so I can update the design a bit?

**Comment by EdddieN** [comment]
What do you think if we move it next to the timer?
![screenshot 2018-11-02 at 11 46 51](https://user-images.githubusercontent.com/39434245/47913850-76d58c00-de95-11e8-8171-481ce1e393a1.png)

**Comment by EdddieN** [comment]
Also, can you explain the logical behaviour of the notification? for example I have it on motion detection:
![screenshot 2018-11-02 at 11 51 37](https://user-images.githubusercontent.com/39434245/47913912-b43a1980-de95-11e8-8569-d3dfe2c24f64.png)
Will the list get bigger and bigger?

My vision was more like a fading banner there. If you are looking at it, you see it fading in and out... if you are not looking at it (web loaded) then it doesn't matter, you can use the log menu on the tile.

Is that how it works?

How big the log goes?
Can we remove the rectangle over it and just leave the text?
Text maybe slightly bigger and bolder?
![screenshot 2018-11-02 at 11 55 26](https://user-images.githubusercontent.com/39434245/47914114-4f32f380-de96-11e8-983e-00a52359fdfb.png)

**Comment by DewGew** [comment]
Log is ulimited for the moment. and if the same message is in the log, it just updates the time. For the moment this device notification just show state or data from selected device. Would be great with a custom message. Viasual notification on a table is a great feature. There is a builtin browser notification in domoticz but I cant get it to work (not on any theme).

![notifications](https://user-images.githubusercontent.com/28799807/47981515-7a068d00-e0cc-11e8-8935-ea0193236d61.png)

**Comment by EdddieN** [comment]
Is that in the beta branch for Domoticz? Maybe is work in progress...  and we are making double work?

I wonder if there's a place to ask that in the forum...

Anyway, I think it would be best to move the icon: https://github.com/EdddieN/machinon-domoticz_theme/issues/165#issuecomment-435354400

as the favourite and alert are too close tapping (at least with my big fingers 😆 )

**Comment by DewGew** [comment]
I think its in all versions..

**Comment by DewGew** [comment]
Is it possible that we mix it with domoticz notifications?
![notifications](https://user-images.githubusercontent.com/28799807/48060234-b533b980-e1bb-11e8-9937-c7a4b390e89e.png)

**Comment by DewGew** [comment]
I remove the rectangle in latest beta..

**Comment by DewGew** [comment]
> Log is ulimited for the moment. and if the same message is in the log, it just updates the time.
> For the moment this device notification just show state or data from selected device. Would be great with a custom message. Viasual notification on a table is a great feature.
> 
> There is a builtin browser notification in domoticz but I cant get it to work (not on any theme).
> 
> ![notifications](https://user-images.githubusercontent.com/28799807/47981515-7a068d00-e0cc-11e8-8935-ea0193236d61.png)

Do you have the above settings in notifications?
I found a way to use this custom message when browser is checked.
@EdddieN 
@landaisbenj

**Comment by landaisbenj** [comment]
Yes I have it on stable.

Benjamin

Envoyé de mon iPhone

Le 6 nov. 2018 à 15:39, DewGew <notifications@github.com<mailto:notifications@github.com>> a écrit :


Log is ulimited for the moment. and if the same message is in the log, it just updates the time.
For the moment this device notification just show state or data from selected device. Would be great with a custom message. Viasual notification on a table is a great feature.

There is a builtin browser notification in domoticz but I cant get it to work (not on any theme).

[notifications]<https://user-images.githubusercontent.com/28799807/47981515-7a068d00-e0cc-11e8-8935-ea0193236d61.png>

Do you have the above settings in notifications?
I found a way to use this custom message when browser is checked.
@EdddieN<https://github.com/EdddieN>
@landaisbenj<https://github.com/landaisbenj>

**Comment by landaisbenj** [comment]
Don't know how it works.

Benjamin

Envoyé de mon iPhone

Le 6 nov. 2018 à 15:39, DewGew <notifications@github.com<mailto:notifications@github.com>> a écrit :


Log is ulimited for the moment. and if the same message is in the log, it just updates the time.
For the moment this device notification just show state or data from selected device. Would be great with a custom message. Viasual notification on a table is a great feature.

There is a builtin browser notification in domoticz but I cant get it to work (not on any theme).

[notifications]<https://user-images.githubusercontent.com/28799807/47981515-7a068d00-e0cc-11e8-8935-ea0193236d61.png>

Do you have the above settings in notifications?
I found a way to use this custom message when browser is checked.
@EdddieN<https://github.com/EdddieN>
@landaisbenj<https://github.com/landaisbenj>

**Comment by DewGew** [comment]
#167

**Comment by EdddieN** [comment]
I think we can close this, DewGew solution is simplest by far 😄 without cluttering the UI
