### ISSUE TITLE
Popup boxes on floorplan

### ISSUE THREAD

**Issue by EdddieN** [EdddieN/machinon-domoticz_theme#169]
See attached
![plan dark](https://user-images.githubusercontent.com/39434245/48217287-e6a8b280-e37e-11e8-8b94-213347216d8c.png)

**Comment by DewGew** [comment]
Hard to get this.. maybe @landaisbenj  can find the right code?

**Comment by EdddieN** [comment]
I'll market as feature request, but not critical. Maybe with the angular update may be a better time to look at it

**Comment by michass** [comment]
Please tell me name of software to 3d model of your home.

**Comment by EdddieN** [comment]
I think Sketch up...

**Comment by bokan20** [comment]
@EdddieN  can you send me the * .skp file of his florplan to bokan20@gmail.com ? Thank you, Bojan

**Comment by DewGew** [comment]
Fixed in latest beta 👍 .. @EdddieN  @landaisbenj https://github.com/EdddieN/machinon-domoticz_theme/commit/934a800c965ecf39435aefcda0ba9c976e3c9b92

**Comment by michass** [comment]
Oh no.....

![image](https://user-images.githubusercontent.com/43785139/54608066-3ba4b580-4a50-11e9-8bcc-1802b1b2a637.png)

**Comment by DewGew** [comment]
I changed font size. Make a git pull and try again

**Comment by michass** [comment]
But can you give an choice? I have light floorplan and dark popups don't look atractive.

**Comment by EdddieN** [comment]
Maybe a full cache, there's the option of light https://github.com/EdddieN/machinon-domoticz_theme/issues/169#issuecomment-474270181

**Comment by michass** [comment]
Yes, there is light option in light theme,
But in dark theme you have only dark popups. I have dark theme, but light floorplan and you see, how it looks like.

**Comment by EdddieN** [comment]
Do you mean you have a dark theme but the floorplan is white?

**Comment by michass** [comment]
exactly,
pleease look:

![image](https://user-images.githubusercontent.com/43785139/55216053-07718780-51fc-11e9-9442-ddbcb4285d16.png)

**Comment by EdddieN** [comment]
I think is very likely that the easier solution is that you invert the floorplan to black background and white lines to be honest.

**Comment by DewGew** [comment]
Changed the text color #237. closing this issue
