### ISSUE TITLE
No options Text devices 

### ISSUE THREAD

**Issue by DewGew** [EdddieN/machinon-domoticz_theme#17]
There is no 3 dotted opion menu on text devices.

**Comment by EdddieN** [comment]
Ok, I see. Hold on fixing as the layout of the tiles is going to change a bit to make more space for text. Also the menu dots will change to horizontal. I'll mark this as design enhancement for now
![screen shot 2018-07-20 at 08 37 55](https://user-images.githubusercontent.com/39434245/42989640-560cf6ce-8bf8-11e8-8eba-bdf62b228472.png)

**Comment by EdddieN** [comment]
This has been updated on Zeplin already with menu horizonal so there's more space for text

**Comment by DewGew** [comment]
But the options should be there anyway. Same issue with pushbuttons.

**Comment by DewGew** [comment]
#83
