### ISSUE TITLE
Notifications optimisation

### ISSUE THREAD

**Issue by EdddieN** [EdddieN/machinon-domoticz_theme#170]
See attached, regardless of the bell being persistent or not, if we use Domoticz in tablet mode, it would be nice to have these flashes without having to tap into the bell to see the log. In fact not all needs to be logged, some thing are not that important to know they happened unless you are looking right now at the screen. (but good to have the option)

![notifications](https://user-images.githubusercontent.com/39434245/48229006-be30b080-e39e-11e8-8253-84be7aa9cf95.gif)

**Comment by EdddieN** [comment]
It is a gif, you'll have to wait to see the text fading in and out. 
The font is just bold there so it is clear, it has no design

**Comment by EdddieN** [comment]
Is fine, don't mind too much about notification logs, imagine a motion sensor, you could end up wiht =50 logs of it. However just having the blinking/fading update of just NOW would be enough. Is that making sense?

**Comment by DewGew** [comment]
it make sense..
