### ISSUE TITLE
Design problem

### ISSUE THREAD

**Issue by GGalloppa** [EdddieN/machinon-domoticz_theme#173]
In temperature i ave strange design problem in Machinon theme V.1.4.2

![immagine](https://user-images.githubusercontent.com/44898622/48263798-a6e9d580-e427-11e8-85ff-f2e7b29f7f74.png)

and if i go on log and go back is ok!

![immagine](https://user-images.githubusercontent.com/44898622/48263839-bc5eff80-e427-11e8-9abb-3943d1d81803.png)

**Comment by landaisbenj** [comment]
maybe fix on futur beta with grid branch

**Comment by GGalloppa** [comment]
Ok tanks

Il giorno Ven 9 Nov 2018, 15:41 landaisbenj <notifications@github.com> ha
scritto:
