### ISSUE TITLE
Fix thermostat setpoint GUI

### ISSUE THREAD

**Issue by EdddieN** [EdddieN/machinon-domoticz_theme#176]
See attached, any chance to update this screen:
![screenshot 2018-11-17 at 08 30 49](https://user-images.githubusercontent.com/39434245/48659029-43713080-ea43-11e8-988b-877cf32377ff.png)

for 
![set temperatue 1](https://user-images.githubusercontent.com/39434245/48659048-8af7bc80-ea43-11e8-9906-1cb66289c2de.png)

It feels like the only thing really broken so far and is driving me crazy 😆  @DewGew @landaisbenj

**Comment by DewGew** [comment]
Looks great. Need to figure out how to apply this..

**Comment by landaisbenj** [comment]
First try:
![capture](https://user-images.githubusercontent.com/32144431/48827707-33708e00-ed6e-11e8-9742-a4460da10c96.PNG)
with:
```
#setpoint_popup tr td:nth-child(1) br,
#setpoint_popup tr td:nth-child(2) br,
#setpoint_popup tr td:nth-child(2) a[id^="popup_temp"] img{
  display:none;
}

#setpoint_popup tr{
  display: grid;
  width: 15vw;
  background: white;
}

#setpoint_popup tr td:nth-child(1){margin: auto;display: block;text-align: center;color: var(--secondary-text-color);
  text-shadow: none;
  font-family: main-font-bold;
}

#setpoint_popup tr td:nth-child(2) a[id^="popup_temp"]:before{
  content: "";
  position: absolute;
  top: 50%;
  width: 1.5vmin;
  height: 1.5vmin;
  background: transparent;
  border-top: 0.1vmin solid var(--main-blue-color);
  border-right: 0.1vmin solid var(--main-blue-color);
  border-radius:2px;
}
  
#setpoint_popup tr td:nth-child(2) a#popup_temp_up:before{  
  transform: translate3d(0, -50%, 0) rotate(315deg);
}

#setpoint_popup tr td:nth-child(2) a#popup_temp_down:before{  
  transform: translate3d(0, -50%, 0) rotate(135deg);
}
```
Need 'set to' (more difficult because i suppose it may display last stat'.
And onClick function SetpointUp() & SetpointDown() on img before

**Comment by EdddieN** [comment]
Getting very close! 😄 

I have edited this one in the meantime so I can see the numbers for now:
https://github.com/EdddieN/machinon-domoticz_theme/blob/master/custom.css

**Comment by DewGew** [comment]
How is this going?

**Comment by EdddieN** [comment]
I think my poor mans last edit is where it is now

**Comment by EdddieN** [comment]
Nice! so can we close this?

**Comment by DewGew** [comment]
Sure why not
