### ISSUE TITLE
Problem layout

### ISSUE THREAD

**Issue by mikeo999** [EdddieN/machinon-domoticz_theme#18]
I have just installed your nice theme. But have two problems.

1.  Missing text from button in Dashboard view.  In Switches the text in there.
2. Layout in Firefox is not correct. In Chrome it looks fine.

http://i67.tinypic.com/1zx2wwx.jpg

**Comment by landaisbenj** [comment]
Hello

1 it's not a problem. Dashboard is in réflexion. 

2 we can look at that.

**Comment by landaisbenj** [comment]
In git hub you do not need tu post pic with other url. You can just copy past here.

**Comment by mikeo999** [comment]
What do you mean with réflexion. 

In Firefox layout is the same, like the example i post,  for all items bye the way.

**Comment by mikeo999** [comment]
Also notice when you click on Settings --> Update Domoticz update is directly starting instead of asking if you whant to update or note, like the default theme. Is a saver if you click on the button and get the question

**Comment by landaisbenj** [comment]
Dashboard is in progess. Thanks for report for update button.

**Comment by EdddieN** [comment]
Two issues here:

Dashboard + layout here: https://github.com/EdddieN/machinon-domoticz_theme/issues/27
Update with no question here: https://github.com/EdddieN/machinon-domoticz_theme/issues/21

Closing these and leaving the other two open, easier to track.
