### ISSUE TITLE
Custom menu bug

### ISSUE THREAD

**Issue by EdddieN** [EdddieN/machinon-domoticz_theme#180]
Enabled custom menu with domoticz default theme. 

Then switch to machinon theme and try to disable the custom menu. It doesn't work.

However if I disable the custom menu on Domoticz default theme, then it dissapears when I switch back to machinon theme

**Comment by DewGew** [comment]
When you enable/disable the custom menu. You have to hit the apply settings button, not save theme settings button

**Comment by EdddieN** [comment]
ahh! that got me tricked... I assumed all the settings on the theme tab are saved with the save theme settings.
