### ISSUE TITLE
Merry Xmas

### ISSUE THREAD

**Issue by DewGew** [EdddieN/machinon-domoticz_theme#189]
I xmas pimped my theme :)
Happy Holidays to you all!

![christmas](https://user-images.githubusercontent.com/28799807/50215461-6749ce00-0383-11e9-8116-3eeec130b7dd.gif)

Do you want to test my xmas theme.  Test Machinon-xmas branch:

`git clone https://github.com/EdddieN/machinon-domoticz_theme --branch Machinon-Xmas machinon-xmas`

@landaisbenj  @EdddieN  @mattlogic

**Comment by EdddieN** [comment]
Hey @DewGew , this is brilliant! Love it!
