### ISSUE TITLE
Proxy URL relative problems

### ISSUE THREAD

**Issue by EdddieN** [EdddieN/machinon-domoticz_theme#190]
See attached, I'm trying NGINX proxy and when I add the /domoticz/ into the URL for the proxy, a lot of errors (not found happen), the settings page does not load
![screenshot 2018-12-19 at 18 36 02](https://user-images.githubusercontent.com/39434245/50241232-e0b2e200-03be-11e9-8904-ea8fd07206c5.png)

Is this a similar problem to this:
https://github.com/EdddieN/machinon-domoticz_theme/commit/9b18f4f761eb8a1626530ab3e9c77068070a1da6

**Comment by EdddieN** [comment]
Using the default theme all works ok. 
The problem exists also on the master branch too

**Comment by DewGew** [comment]
why do you add /domoticz/ to url ? do you have a subfolder named domoticz in www?

**Comment by EdddieN** [comment]
I’m proxyinf Domoticz vía an external server so I do now need to open my firewall (reverse proxy)

Still a bit tender to test but if you are up for it to try this holidays I can give you access to the repositories....

You can use my server to proxy you Domoticz unit

**Comment by EdddieN** [comment]
Issue solved here: https://github.com/EdddieN/machinon-domoticz_theme/pull/191
