### ISSUE TITLE
One thing

### ISSUE THREAD

**Issue by landaisbenj** [EdddieN/machinon-domoticz_theme#192]
https://github.com/EdddieN/machinon-domoticz_theme/blob/afa45b470e7d1c242c6dfbbf7c2084f4f49671b7/custom.js#L203

@DewGew do you know if is it a reason to don't make a media queries css rules ?

**Comment by DewGew** [comment]
Its was written like that from the beginning, before I joined the team

**Comment by landaisbenj** [comment]
Ok thanks
