### ISSUE TITLE
Problem theme

### ISSUE THREAD

**Issue by bokan20** [EdddieN/machinon-domoticz_theme#193]
Hello, 
i still have this problem. I worked clear cache and open chrom Ctrl+Shift+N
Machinon theme V.1.5.0
Same problem and on iPAD and Android

![1](https://user-images.githubusercontent.com/46202245/50495642-b1d5e500-0a2a-11e9-9ab4-347a8c0e7b78.jpg)

**Comment by EdddieN** [comment]
https://github.com/EdddieN/machinon-domoticz_theme/issues/184 merged here
