### ISSUE TITLE
Background of image Alert48_2.png is not transparent

### ISSUE THREAD

**Issue by davidlb** [EdddieN/machinon-domoticz_theme#194]
Just a small issue, the background of the image file [Alert48_2.png](../blob/master/images/Alert48_2.png) is grey and not transparent

![Alert48_2.png](https://raw.githubusercontent.com/EdddieN/machinon-domoticz_theme/master/images/Alert48_2.png)

**Comment by EdddieN** [comment]
Tried to replace it but I think the server is caching, maybe it will refresh later... anyway here it is attached just in case
![alert48_2](https://user-images.githubusercontent.com/39434245/50918328-d45afb80-1437-11e9-93f6-d722669135ab.png)

https://github.com/EdddieN/machinon-domoticz_theme/commit/7c2f0cc65a0e434c644b11d745372bfcf53fd33d?short_path=99cb5b3#diff-99cb5b35db04e5245490f832052dd806
