### ISSUE TITLE
Settings.html is missing

### ISSUE THREAD

**Issue by hydex80** [EdddieN/machinon-domoticz_theme#195]
When installing the theme the wiki says: 
sudo cp ~/domoticz/www/styles/machinon/templates/Settings.html ~/domoticz/www/templates/

But there is no Settings.html in /machinon/templates but there is a themesettings.html. 

I renamed the file to Settings.html and got it working. Please change the file name in the build on GitHub.

**Comment by EdddieN** [comment]
Extrange, according to github there's:
https://github.com/EdddieN/machinon-domoticz_theme/tree/master/templates
