### ISSUE TITLE
Lost original settings menu item

### ISSUE THREAD

**Issue by hydex80** [EdddieN/machinon-domoticz_theme#196]
I only see a settings menu of machinon, but the original settings menu of domoticz has been disappeared. And I cannot save settings of the machinon settings menu. Value's are not stored.

**Comment by EdddieN** [comment]
Have you tried this? sudo cp ~/domoticz/www/styles/machinon/templates/Settings.html ~/domoticz/www/templates/

**Comment by hydex80** [comment]
your right, I made a mistake, cp the wrong file. This item can be closed
