### ISSUE TITLE
Another way to setting page

### ISSUE THREAD

**Issue by landaisbenj** [EdddieN/machinon-domoticz_theme#198]
https://github.com/EdddieN/machinon-domoticz_theme/blob/17b2e2aca6752cba49cdb63f6999d28484ded895/custom.js#L82

NB: Juste see how i make the setting page without custom page:
ajax:
https://github.com/landaisbenj/test/blob/c57b102b9e2261c5805fb2bd0124a60af197cef3/custom.js#L6
code:
https://github.com/landaisbenj/test/blob/master/js/setting_page.js

Maybe for futur feature.

**Comment by DewGew** [comment]
Works great 👍

**Comment by EdddieN** [comment]
Wow! That is magic! 😎 anything that makes things simpler...

**Comment by DewGew** [comment]
Added to beta
