### ISSUE TITLE
Responsive breakpoints - number of columns

### ISSUE THREAD

**Issue by davidlb** [EdddieN/machinon-domoticz_theme#201]
Hello,
I like the fact the number of columns is responsive but number of columns in breakpoints should be reviewed. Indeed, on my laptop, resolution is 1366x768 and it would be better to display 3 columns instead of 4 (see below)

![image](https://user-images.githubusercontent.com/12050155/52116908-b0dc3880-2612-11e9-90f6-6abd9eaa518f.png)

**Comment by landaisbenj** [comment]
Thanks for issue. It's not the number of column the probleme. It's the "responsive" of all child.
If you use a bigger screen, you may use a smaller tip. But for the moment, we don't apply this.. It's my futur job.

**Comment by landaisbenj** [comment]
@davidlb did you think you can solve this with last thoughts ?

**Comment by davidlb** [comment]
Yes, I'll give a try next week

**Comment by davidlb** [comment]
It's on the way, I moved to CSS grid --> https://github.com/davidlb/machinon-domoticz_theme/tree/css-grid

**Comment by davidlb** [comment]
Fixed in beta #233
