### ISSUE TITLE
visual bug with SSL connection

### ISSUE THREAD

**Issue by Potjoe-97** [EdddieN/machinon-domoticz_theme#202]
Hi everyone, 
My sd card crashed, I was waiting for a new one, that's why I could'nt test the fix for the tiles. 
I've done a full from scratch install of raspbian, domoticz and machinon theme. No problem on my laptop, but here is the visual on my phone using chrome, android 9.0. The result is the same in mobile mode and desktop mode. 
![unnamed](https://user-images.githubusercontent.com/42873357/52181411-b93e9a00-27f1-11e9-8a98-659e8f5b2de2.jpg)
I cleaned the cache from the settings, not changing anything. 
 #184 #200 

Edit: solved, was a problem with SSL configuration. Closed.

**Comment by Potjoe-97** [comment]
I reopened the issue because the behaviour seems really weird. I have a domain name for my IP address, and the router transfer the traffic to the pi. While accessing inside the sub-net on https by typing de local ip of the Raspberry, absolutely no problem. However, accessing to it

**Comment by Potjoe-97** [comment]
That's really weird. I have a freebox too, with a domain name type xxxxxxxxxx.freeboxos.fr
Rerouting to the port 8080 and connecting with http, no problem inside and outside local network.

**Comment by Potjoe-97** [comment]
Ok I solved it... I set up a port forwarding in the freebox to avoid 443, don't know why it didn't like the one I had before my clean install. Changing the forwarded port solved the issue. Not totally sure why (the behaviour was on all mobile devices, even some which never displayed domoticz instance so not a cache pb)

**Comment by landaisbenj** [comment]
Like me. Nat routing on 8080 and 443 and no problem with both. But I don't have let's enscrypt ...(?)

**Comment by landaisbenj** [comment]
Good for us 😄

**Comment by Potjoe-97** [comment]
Yes hahah ! Actually the first time I see the result on mobile, I am so impressed by the job you've accomplished. Waouh 😃 and congrats ;)

**Comment by landaisbenj** [comment]
Yes thanks but really need a big cleanup and simplification of all code. But for the moment I appreciate the skin 😂
