### ISSUE TITLE
Type: and Status:

### ISSUE THREAD

**Issue by DewGew** [EdddieN/machinon-domoticz_theme#204]
I think we remove `Type:` and `Status:` from tiles in css-file. The theme looks more clean and I think theme loads a bit faster without those.

![tile](https://user-images.githubusercontent.com/28799807/52473271-a6331d80-2b95-11e9-9d2c-6eca0c39c119.png)

**Comment by davidlb** [comment]
I agree and I would go further and remove the full line Type as it's rather useless.

**Comment by EdddieN** [comment]
I would agree on removing both too

**Comment by DewGew** [comment]
Removed those in beta https://github.com/EdddieN/machinon-domoticz_theme/commit/7d4e0e8c716ff07aa7e85bd43e66c5c311b52e39
