### ISSUE TITLE
[Function Request] Hide Dew Point in temp

### ISSUE THREAD

**Issue by Adefx** [EdddieN/machinon-domoticz_theme#206]
this functionality is available in aurora theme... you can hide the dew point , because this information isn't really important for many people (they don't even know what it is )
![hide dew point](https://user-images.githubusercontent.com/20320665/52826957-2b04c680-30c3-11e9-85c5-f67e605d0a3b.PNG)

**Comment by EdddieN** [comment]
I personally find it useful....

**Comment by Adefx** [comment]
For the External meteo yes, of course, but the dew point of your living room .... ;-)
Hidding doesn't mean suppressing

**Comment by davidlb** [comment]
I checked how it's done in Aurora theme, it's on search for string "Dew Point", so it does not work for other languages. I didn't find a better way to identify it with css selectors as there is no class / DOM element.
