### ISSUE TITLE
messy display when have large switch names 

### ISSUE THREAD

**Issue by RowanRivierenland** [EdddieN/machinon-domoticz_theme#218]
![image](https://user-images.githubusercontent.com/42584420/54872955-c37e1d00-4dcc-11e9-9f13-be20b383ae70.png)
![image](https://user-images.githubusercontent.com/42584420/54872966-266fb400-4dcd-11e9-8b36-10aea4b5583f.png)

**Comment by davidlb** [comment]
It should be better (not perfect yet) with last release

**Comment by davidlb** [comment]
It's on the way, I moved to CSS grid --> https://github.com/davidlb/machinon-domoticz_theme/tree/css-grid

**Comment by DewGew** [comment]
#233

**Comment by davidlb** [comment]
Fixed in beta #233
