### ISSUE TITLE
Store permanently theme settings

### ISSUE THREAD

**Issue by EdddieN** [EdddieN/machinon-domoticz_theme#224]
I know for now the settings are stored on a cookie or similar for things like dark theme, menu, icons... would it be possible to store those settings a bit more permanently?

For example everytime I do a git pull and clear cache, I need to re-set everything. Is not that much work, but it would be more tidy. 

I know in the past @DewGew and I talked about using user variables as the Aurora theme, is there any other alternative?

**Comment by DewGew** [comment]
I started out with this https://github.com/EdddieN/machinon-domoticz_theme/tree/DewGew-Save_To_UserVariable
Just need to add custom logo and custom page text variables

**Comment by EdddieN** [comment]
is it worth keeping the custom logo? It is something that can be easily done by replacing the jpg or png file, right?

**Comment by DewGew** [comment]
#230

**Comment by EdddieN** [comment]
Yes I think it is not needed. Can we then close this? I see it has been merged
