### ISSUE TITLE
Iframe question

### ISSUE THREAD

**Issue by andyyyy2306** [EdddieN/machinon-domoticz_theme#225]
Hi, i use machinon theme 1.6.9
I like to use the Iframe feature for my camera. when i open the cameraurl direct the picture is centered. but when i use machinon thre picture is on the left side.

![grafik](https://user-images.githubusercontent.com/46449594/55221958-fe3be700-520a-11e9-8b7b-22bb1ebe1b90.png)

Andyyyy

**Comment by EdddieN** [comment]
Don't know enough of html but.... https://stackoverflow.com/questions/24071390/horizontally-centering-an-images-in-an-iframe-within-a-div

**Comment by DewGew** [comment]
You have to make a html page to open the image url in center then add this new page e.g: ../templates/custompage.html

**Comment by DewGew** [comment]
@andyyyy2306 
Create html document in www folder e.g cameras.html
Add this:
```
<style>
img {
  display: block;
  margin-left: auto;
  margin-right: auto;
}
h2 {
    color: #FFF; <!-- add #000 for black text -->
}
</style>
<br>
<h2 align="center">Camera 1</h2>
<br>
<div>
<a href="javascript:SwitchLayout('cam')"><img alt="video" id="imgDisplay" name="cam name" src="http://192.168.10.125:92/snapshot.cgi?user="user text"&pwd="password text"" width="480" height="360"></a>
</div>
```
Then add "../cameras.html" at iframe url in theme settings

![center_camera](https://user-images.githubusercontent.com/28799807/56718912-01f65700-6740-11e9-833e-cdc8586af5c9.png)

**Comment by andyyyy2306** [comment]
@DewGew 
Thank you Q 
That works great for me..
