### ISSUE TITLE
Timer visual artefact

### ISSUE THREAD

**Issue by EdddieN** [EdddieN/machinon-domoticz_theme#235]
Anyone get this timer visual artefact when used?
If timer has no times is looks ok, but when it has timers setup it looks to me like this
![Screenshot 2019-04-19 at 22 16 53](https://user-images.githubusercontent.com/39434245/56444520-07dbda80-62f1-11e9-984d-55e6bf8fb6ca.png)
![Screenshot 2019-04-19 at 22 17 12](https://user-images.githubusercontent.com/39434245/56444521-07dbda80-62f1-11e9-95a2-482330ff4cfe.png)

**Comment by DewGew** [comment]
I have the same issue

**Comment by ben33880** [comment]
me too, note that menu (3 points) is at the right also.
![a](https://user-images.githubusercontent.com/14923772/56526479-9ef09e80-654c-11e9-8058-46f9f7137aad.png)
