### ISSUE TITLE
Iconset Machinon (eg. Doorbell is missing)

### ISSUE THREAD

**Issue by chrislader** [EdddieN/machinon-domoticz_theme#238]
What iconset is used as a basis for the machinon theme?

I am a icon designer and love to contribute to expand the iconset to some that are not included yet. Love the theme!

Example: 
- doorbell
- counter (on floorplan)
- gas icon (p1 smart meter)
etc

**Comment by DewGew** [comment]
Added doorbell, utility(counter) icons to beta

**Comment by chrislader** [comment]
@DewGew thanks for the doorbell

Can you point me to the theme pack? Or is it privately made? 

There are like 15 icons that I made myself now to fit all missing icons, but it would be much easier if I could access the pack

**Comment by DewGew** [comment]
create a fork then add the icons in image folder in your fork the make pull request to beta branch

**Comment by EdddieN** [comment]
> What iconset is used as a basis for the machinon theme?
> 
> I am a icon designer and love to contribute to expand the iconset to some that are not included yet. Love the theme!
> 
> Example:
> 
> * doorbell
> * counter (on floorplan)
> * gas icon (p1 smart meter)
>   etc

It was done from scratch, original vectors are in Zeplin if you want access. Check out the unorganised folder, there're more there

**Comment by chrislader** [comment]
Ok, can close this thread.

@DewGew ive forked and did a request for some icon additions. I just did a few and ll keep some at my side because they are taste-dependant as well.

**Comment by DewGew** [comment]
@chrislader I saw that you have a form. But you made a PR to your own form. When you make a pull request chose edddie/machinon-Domoticz-theme beta branch in first selector then your patch in second selector

**Comment by EdddieN** [comment]
> Ok, can close this thread.
> 
> @DewGew ive forked and did a request for some icon additions. I just did a few and ll keep some at my side because they are taste-dependant as well.

The more options the better, share as much as you can 😄
