### ISSUE TITLE
Dashboard improvement suggestions | Mobile?

### ISSUE THREAD

**Issue by chrislader** [EdddieN/machinon-domoticz_theme#239]
Hi there,

A little 'stolen' from the Aurora theme; 2 improvement suggestions;

1. Option in settings to remove titles of device types on dashboard screen (in mockup: red)

2. Much more compact tiles on dashboard screen making it a little bit more of a real dashboard. In aurora theme the tiles can be made so compact that they are virtually 'lines'

![mockup_1](https://user-images.githubusercontent.com/40333466/56717737-9d39fd00-673d-11e9-8072-ea6e295843d0.png)

**Comment by davidlb** [comment]
I can add an option to have a compact dashboard layout.

**Comment by landaisbenj** [comment]
First idea by @EdddieN was this:

[](https://user-images.githubusercontent.com/32144431/43963139-ce5d6d26-9cb9-11e8-89c1-73bdb3166132.png)

Something like that was pretty good. Easy with flex or grid...

**Comment by chrislader** [comment]
Great. Looks like Apple Homekit devices overview.

How about this: 
![image](https://user-images.githubusercontent.com/40333466/56749696-81a51580-6782-11e9-8ee9-a798f74695a9.png)

This way you would keep the dimmer options straight from dashboard.

**Comment by davidlb** [comment]
To get the compact dashboard, in Domoticz settings (not theme settings) set Dashboard mode to Compact.

**Comment by chrislader** [comment]
@davidlb Looks a million times better now, but I am not sure if you intentionally also made the tiles in the menus at switches, temps, utils etc smaller? I think they are better there as well. Looks slick now.

Can you make the titles on dashboard optional as well? like in my first screenshot: the red striped area.

**Comment by chrislader** [comment]
Camera preview going wrong in new setting, little bit too flat.
![image](https://user-images.githubusercontent.com/40333466/56847859-b67bae80-68e1-11e9-80fe-4790a0faff96.png)

**Comment by chrislader** [comment]
Really like where this is going to. Few suggestions (annotated in blue);

- text alignment of titel to left
- little bit more distance between dim slider and button
- categorie icon alignment as an acolade centered in the middle
- icon size can also be like 80%; same goes for flip switch?

![image](https://user-images.githubusercontent.com/40333466/56847969-09a23100-68e3-11e9-9cbf-da748e83378e.png)

**Comment by EdddieN** [comment]
Just butting in, Should not the super-compact view be designed with mobile access in mind?

**Comment by chrislader** [comment]
@EdddieN I'm with you on this and solved it as follows;

I use a native app (so answering your 1st question: I think not; these are 2 things) on my iPhone AND iPad 'Pilot' to fully suit mobile needs. The problem with feature rich mobile websites is that simply they are not snappy enough compared to dedicated apps (eg. the dimslider). If you move into this direction you switch to Xamarin / Mendix / etc using webcode together with native mobile code.

Thus yes; you are pointing out an important difference; the compact view we are trying to get here is an overview / dashboard approach for desktop, not so much a mobile 'overview'. These are different things.

You could argue to get mobile browser detection on your dashboard website giving you a view that I mocked up in a earlier post... that might be a hybrid solution.

**Comment by chrislader** [comment]
Here is a mobile app view from Pilot, as you see complete different than the mobile view approach from ‘dashboard’

![Image](https://i.imgur.com/eaElbJC.jpg)

**Comment by EdddieN** [comment]
Yes I have paid version of all the Domoticz compatible ones (Pilot, Domoticz, Domotix, Imperihome...) yet I keep going back to Homekit as it find it the fastest and more intuitive.

I remember a while back someone did a web version of it for Domoticz, if I can find it I'll post the link, it was on the forum

**Comment by EdddieN** [comment]
Found it! https://www.domoticz.com/forum/viewtopic.php?f=8&t=12909&p=117564#p117564
https://github.com/andrewatwood/homeAppFrontend

I think it would be great if we could do something similar: https://streamable.com/iis1 More than happy to work on the design if viable

**Comment by chrislader** [comment]
@EdddieN I think we need to keep 3 things seperated;

1. [Desktop]
The Desktop dashboard (as intended by Gizmocuz). This is what we try to achieve above. Get a beautifull overview off all switches and sensors into 1 view. 

2. [Hybrid mobile]
When this dashboard gets opened on a mobile device you apply something fancy. I think we have 2 options here; a responsive version where tiles are sorted as lines as seen in mockup. Second option here is to switch to a homekit approach as demonstrated by andrewatwood. So here you need to push mobile_detection to active that widget (and it looks like it is mainly oriented at switches

3. [Native mobile]
A snappy dedicated app using all the options from a mobile device, like push notifications, widget integration, smartwatch, geolocation, etc. Examples already given above.

**Comment by EdddieN** [comment]
I think option 1 and 2 are reasonable. Option 3 probably requires other skills beyond web coding, although with PhoneGap or something like that may be possible 

Option 2) -> Do we go standard Dashboard or do we go something more like HomeKit?

**Comment by DewGew** [comment]
In the new dashboard. last seen is under the tiles.

![dashboard](https://user-images.githubusercontent.com/28799807/56877907-86531d80-6a51-11e9-878f-dcf3097a9416.png)

**Comment by DewGew** [comment]
> Found it! https://www.domoticz.com/forum/viewtopic.php?f=8&t=12909&p=117564#p117564
> https://github.com/andrewatwood/homeAppFrontend
> 
> I think it would be great if we could do something similar: https://streamable.com/iis1 More than happy to work on the design if viable
> 
> I forked here and contacting the original author: https://github.com/EdddieN/homeAppFrontend

Looks promising.

**Comment by EdddieN** [comment]
yes it does indeed! Last time I tried was quite light on the phone

**Comment by mrrioes** [comment]
Did you guys had a look at Reacticz? https://github.com/domoticz/Reacticz
I guess I´m the last one qhos using it but find it very respnsive and I like the fact that it is customizable.
Unfortunately it seems not to get any support anymore.

**Comment by davidlb** [comment]
Yes, I know Reacticz, I worked on it, it's really cool for dashboard. But you cannot manage domoticz from it.

I'll look at bugs next week when I'll be back from vacations.

**Comment by chrislader** [comment]
@davidlb great! give me an @ when youre working on it. Can test quite fast and with lots of different sensors and devices (250+ here in the system)

Besides the remarkes from above, some extra thoughts;
- When using devices with multiple labeled custom buttons; this will almost never fit; I suggest just showing the active one. Example:

![image](https://user-images.githubusercontent.com/40333466/57014096-ca3f5180-6c0e-11e9-9b9f-1557b4fcc2c7.png)

**Comment by chrislader** [comment]
@davidlb 

I can confirm the fixed camera tile when last in row (in normal mode)

For the compact mode: I attached the screenshot below. Again great to see the improvements coming, great work.

- Space between slider + switch is still a bit too tight I think. Also it looks like they only show when lights are RGBWW and not WW (then there is only a slider, no switch)
- Utility doesnt show current values; I suggest removing the extended info and replace by just the actual value (as now done for temperatures)
- I would make the categorie icons on the left side optional through the settings menu or leave em out; I think they are not aligned with the simplistic style. Maybe it's just taste, but I personally would remove them including the suble edge around the category


![image](https://user-images.githubusercontent.com/40333466/57244213-3ae3d500-7038-11e9-96f5-da74ca3c50ff.png)

**Comment by chrislader** [comment]
@davidlb TOP job!

- There is a small subtle white line surrounding the categories; I would remove it
- Utility shows extra info; I think this should be removed as well
![image](https://user-images.githubusercontent.com/40333466/57325090-916d1400-7109-11e9-8516-9380d09b0ad2.png)

**Comment by davidlb** [comment]
@chrislader it should be ok now, keep me informed if you find other bugs :)

**Comment by chrislader** [comment]
Not sure what happened, but I can not update beta anymore?

![image](https://user-images.githubusercontent.com/40333466/57409052-91434600-71e7-11e9-84be-7dd210894b95.png)

**Comment by davidlb** [comment]
DId you make any change in your repo?
Try:
```
git fetch
git reset --hard origin/beta
```

**Comment by DewGew** [comment]
I have issue as chrislader. No change done

**Comment by davidlb** [comment]
Damn, I cannot reproduce it, I have been able to update an old repo and tried from a fresh clone.
I think it's after my git rebase to remove a bad commit message but I cannot find any useful articles to help you

**Comment by chrislader** [comment]
@davidlb 
I can pull again after applying your pieces of code
Let me check

**Comment by chrislader** [comment]
Looking sharp David! I will bughunt the coming days ahead. But first impressing is very good.

![image](https://user-images.githubusercontent.com/40333466/57482573-40922280-72a5-11e9-8311-c93793c19068.png)

**Comment by chrislader** [comment]
iPad:

![image](https://user-images.githubusercontent.com/40333466/57482822-e6de2800-72a5-11e9-8f41-4669571acf06.png)

**Comment by chrislader** [comment]
iPhone X. Here is where the hybrid theory comes in.

![image](https://user-images.githubusercontent.com/40333466/57482859-02e1c980-72a6-11e9-831d-c4bfcfc99faa.png)

**Comment by DewGew** [comment]
> Damn, I cannot reproduce it, I have been able to update an old repo and tried from a fresh clone.
> I think it's after my git rebase to remove a bad commit message but I cannot find any useful articles to help you

I know whats wrong.. I uploaded some images. That's way I got error. Maybe create a "custom" folder and put user changed files there and change the paths in js files and add this folder to ignore list.

**Comment by chrislader** [comment]
@davidlb I tested a lot of combinations. No bugs yet. Only thing I can remark is the distance between the switch and the text. If you are able to put it down a few pixels then it would be perfect I think.

![image](https://user-images.githubusercontent.com/40333466/57550960-15bcd280-7368-11e9-9d74-22068299fc46.png)

**Comment by chrislader** [comment]
Dashboard in columns goes wrong:

![image](https://user-images.githubusercontent.com/40333466/57552804-49e6c200-736d-11e9-9522-8d1d3989798e.png)

**Comment by chrislader** [comment]
I think mobile for webbased approach looks great now. Considering this is web only.

![Image](https://i.imgur.com/AOIl4KP.jpg)
![Image](https://i.imgur.com/XFSctn9.jpg)

**Comment by davidlb** [comment]
Thanks @chrislader for your comments! I'll fix them.

**Comment by EdddieN** [comment]
WoW this is really nice, I had been very busy at work so took me a while to test all the new features.
Great work!

Here is thought, the same way that we have a mobile view for the dashboard, can it be used for the rest of the tabs? Is there space for mini icons?

**Comment by chrislader** [comment]
@EddieN

Have you the new Pilot app (released yesterday). Complete overgaul. Redesign based upon homekit tiles, exactly how you described. Your prayers have been answered ;)

![Image](https://i.imgur.com/x2s00fq.jpg)

![Image](https://i.imgur.com/1PLuLQT.jpg)

**Comment by chrislader** [comment]
@davidlb 
Just tested your fixes for the mobile webpage.
- The width is now perfect
- The sun icon is now removed (my suggestion was to replace it by the black icon one, but this is also fine)
- I noticed that when showing "dummy" devices it uses a different icon instead of a blue arrow before the device

**Comment by EdddieN** [comment]
> @EdddieN
> 
> Have you already seen the new Pilot app (released yesterday)? Complete overhaul. Redesign based upon homekit tiles, exactly how you described. Your prayers have been answered ;)
> 
Brilliant! Can't wait to see the update on mine, for whatever reason it hasn't appeared on the my Appstore... patience I guess.

**Comment by chrislader** [comment]
@davidlb Just did a full retest of everything. 
Like the new sharp icons; they look great!

My remarks are:

- text size of titels in compact mode on dashboard is slightly larger than in normal mode and on the other tabs. If you could match it it would be great.
- in compact mode: vertical colums still has a visual bug; the first column is smaller
- I love to see the full time + black sun icon return in web mobile mode. But thats just taste I think ;)

All above is ofcourse nice to have. The dashboard looks really nice! Keep up the good work

**Comment by davidlb** [comment]
Thanks @chrislader for all relevant comments!
Last commit shoud fix them all :)

**Comment by chrislader** [comment]
@davidlb 

Thanks for all the last fixes, you did an absolute brilliant job in bringing a real desktop dashboard back to Machinon/Domoticz. My compliments (and probably all of the other users as well)!!!

I ll close this topic now. Other bugs/ideas/findings etc, we ll do in a new issue.
