### ISSUE TITLE
Floorplan: floors not visible

### ISSUE THREAD

**Issue by chrislader** [EdddieN/machinon-domoticz_theme#240]
On Floorplan tab, the other floors are not visible untill you mouseover the buttons;

![image](https://user-images.githubusercontent.com/40333466/56718076-64e6ee80-673e-11e9-81c2-c5ccd97a7796.png)

I have 4 floors:

![image](https://user-images.githubusercontent.com/40333466/56718192-95c72380-673e-11e9-831a-653648641b78.png)

Makes it difficult to switch between floors.

**Comment by DewGew** [comment]
Try beta.

**Comment by chrislader** [comment]
Much better now! Just a small extra suggestion; the mouseover color is now a different color blue. Not a big deal, but if you want the full ten points, you might want to change that to the same color blue as the whole theme.

![image](https://user-images.githubusercontent.com/40333466/56725165-9ff01e80-674c-11e9-8a7a-03ce415afbb5.png)

**Comment by DewGew** [comment]
@chrislader You change the hover color in settings/floorplan.
Change room area color to #0b96cd
