### ISSUE TITLE
Visual improvements in buttons (menu)

### ISSUE THREAD

**Issue by chrislader** [EdddieN/machinon-domoticz_theme#241]
Again not a big deal, but I find buttons in different styles throughout the theme. 

Example: buttons in different menus are blue and black, while at other places it is blue with white (more apealing). Below at hardware:

![image](https://user-images.githubusercontent.com/40333466/56728384-f4969800-6752-11e9-9e84-7eff2f39b9ef.png)

The Z-wave menu:

![image](https://user-images.githubusercontent.com/40333466/56728432-0d06b280-6753-11e9-8301-e4a0f11172bf.png)

I'd say lets make this theme the best ever!

**Comment by davidlb** [comment]
I don't have Zwave devices, can you give me CSS classes of the green button (Groups & Network)?

**Comment by chrislader** [comment]
Ah, that explains it. The entire menu is still in 'old style'. Here is one fix:

in custom.css, change:
![image](https://user-images.githubusercontent.com/40333466/56746708-0ab94e00-677d-11e9-9630-523233661b90.png)

To:

.btn-warning{
  background: none;
  border-color: #FF8C00;
  color: #FF8C00;
  border-radius: 1px;

This fixes the orange button.

and the green button is in bootstrap.css:

![image](https://user-images.githubusercontent.com/40333466/56746988-80bdb500-677d-11e9-99f8-2fbab62ffed9.png)

**Comment by chrislader** [comment]
Green button opens the following menu:

![image](https://user-images.githubusercontent.com/40333466/56747127-b2368080-677d-11e9-892b-063455a9d6fe.png)

Menu is old style

**Comment by DewGew** [comment]
More visual improvement https://github.com/EdddieN/machinon-domoticz_theme/commit/1f1efc9f7c812d5861745979b565619faf87e837
