### ISSUE TITLE
Message Box about theme settings in uservariable

### ISSUE THREAD

**Issue by niawag** [EdddieN/machinon-domoticz_theme#242]
Hi all and thanks for this really nice theme!

I've updated to 1.7.2 (from 1.6.?) with a git pull, I restarted Domoticz and cleared appcache and the theme version is ok in the settings (so everything is as it should). I'm facing a problem when reloading my Domoticz (4.9700) WebUI, I'm getting two message boxes (I need to close the first one to see the other) with the same text: "Unable to create or update theme settings uservariable, Try to reset the theme" -->resetted the theme, same problem
I've checked the User Variables in domoticz settings and there is none.
There is nothing unusual in the logs

What can I test now? Where should I look?

**Comment by Alindil** [comment]
Hi, I have the same problem.

**Comment by DewGew** [comment]
Sometimes when I have strange faults I have to change theme to default then switch back to machinon.
else try to reneme old machinon theme folder and make new git pull and try again.

**Comment by Alindil** [comment]
I've already deleted the theme directory and made a git pull. When looking at the message, shouldn't a uservariable be created? Because I don't have any news

**Comment by DewGew** [comment]
It creates when you press 'save theme settings'

**Comment by Alindil** [comment]
When I click on the button, I get the same message "Unable to create or update theme settings uservariable, Try to reset the theme". And no variables are created

**Comment by DewGew** [comment]
Maybe its domoticz versions. I have run domoticz latest beta i cant reproduce this issue.

**Comment by niawag** [comment]
Maybe we could try to add the user variables manually? What are the names and types of these variables?

**Comment by DewGew** [comment]
hit F12 and look at console log if there is any errors

**Comment by niawag** [comment]
I'm having errors with fonts:
> Mixed Content: The page at 'https://domoticz.server/#/Dashboard' was loaded over HTTPS, but requested an insecure font 'http://themes.googleusercontent.com/static/fonts/inconsolata/v5/BjAYBlHtW3CJxDcjzrnZCIbN6UDyHWBl620a-IRfuBk.woff'. This request has been blocked; the content must be served over HTTPS.

No error other than that, but some Machinon related log:
> Machinon - theme settings was already found in the browser.
> Machinon - Loading javascript for check_update feature
> Machinon - feature files is loaded.
> Machinon - Javascript loaded by RequireJS

And a lot of these:
> [Violation] 'setTimeout' handler took 234ms
> [Violation] 'setInterval' handler took 157ms

**Comment by DewGew** [comment]
Try this.. replace themesettings.js in machinon/js folder with this file 
[themesettings.js.txt](https://github.com/EdddieN/machinon-domoticz_theme/files/3120301/themesettings.js.txt) (Rename it to themesettings.js)
Then try again

**Comment by davidlb** [comment]
> I'm having errors with fonts:
> 
> > Mixed Content: The page at 'https://domoticz.server/#/Dashboard' was loaded over HTTPS, but requested an insecure font 'http://themes.googleusercontent.com/static/fonts/inconsolata/v5/BjAYBlHtW3CJxDcjzrnZCIbN6UDyHWBl620a-IRfuBk.woff'. This request has been blocked; the content must be served over HTTPS.
> 

Strange, we don't download anymore fonts from Google, they are store localy to avoid this kind of error and in case people are running domoticz with no internet connection.

Can you clear the local cache?

**Comment by Alindil** [comment]
It's okay I don't have the message anymore and the uservariables are well created

**Comment by DewGew** [comment]
@Alindil Did you change anything?

**Comment by Alindil** [comment]
I just replaced the themesettings.js file and clicked on "Save theme settings"

**Comment by niawag** [comment]
Also working for me with the themesettings.js file you provided.
@davidlb 
I cleared local cache, cookies and app cache and am still having the same issues (not in private mde though):
> jquery-3.3.1.min.js:2 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
> send @ jquery-3.3.1.min.js:2
> ajax @ jquery-3.3.1.min.js:2
> (anonymous) @ custom.js:9
> 6Mixed Content: The page at '<URL>' was loaded over HTTPS, but requested an insecure font '<URL>'. This request has been blocked; the content must be served over HTTPS.
> (index):123 Uncaught TypeError: generate_noty is not a function
>     at NotifyCacheRefresh ((index):123)
>     at ApplicationCache.<anonymous> ((index):318)

Not a big deal as everything is working well now.

THANKS a lot for your help!

**Comment by DewGew** [comment]
Problem is domoticz API handle uservariable diffrent in before V4.10456.
https://github.com/domoticz/domoticz/issues/3067
