### ISSUE TITLE
More UI small visual bugs

### ISSUE THREAD

**Issue by chrislader** [EdddieN/machinon-domoticz_theme#245]
Some more UI bugs found;

In settings tab -> about: should be white text
![image](https://user-images.githubusercontent.com/40333466/56846590-5e3cb080-68d1-11e9-9f44-6fe3ed801383.png)

In Settings -> devices tab -> boxes should be blue

![image](https://user-images.githubusercontent.com/40333466/56846628-b378c200-68d1-11e9-91ef-82859e0bc5b3.png)

Fix is here: 
![image](https://user-images.githubusercontent.com/40333466/56846642-eae76e80-68d1-11e9-8bea-82a120ceda54.png)

**Comment by EdddieN** [comment]
I think I mixed up links.... now sure how to delete the above

**Comment by DewGew** [comment]
@EdddieN Edit the comment in 162
