### ISSUE TITLE
Unable to create or update theme settings uservariable, Try to reset the theme

### ISSUE THREAD

**Issue by Potjoe-97** [EdddieN/machinon-domoticz_theme#248]
Hello everyone, 

After upgrading to 1.7.2, and despite a cache clear and refresh, I have an error when opening domoticz with machinon theme "Unable to create or update theme settings uservariable, Try to reset the theme". I tried in private navigation mode, same troubles, and I've done a clean install of machinon theme, same thing. 

Clicking the "ok" button in the window where is displayed the message give me access to the dashboard so it's not that bad, let's consider this issue as a bug report.

**Comment by DewGew** [comment]
Same as #242
