### ISSUE TITLE
[Firefox] theme.logo is null

### ISSUE THREAD

**Issue by DarkAllMan** [EdddieN/machinon-domoticz_theme#259]
Logo not showing :)
Console says: theme.logo is null

**Comment by DewGew** [comment]
clear localstorage

**Comment by DarkAllMan** [comment]
I already did that.
Just did it again to confirm... but it did not solve the issue.
When I tried another browser (chrome) it shows the logo... so it must be a browser issue.... need tot check what is going on there.

**Comment by davidlb** [comment]
What's your browser?

**Comment by DarkAllMan** [comment]
Firefox

Op wo 15 mei 2019 17:50 schreef David Le Brun <notifications@github.com>:

**Comment by davidlb** [comment]
I cannot reproduce it on Firefox 66.0.5 (Win64) but I had to remove local storage --> Press F12 to open the Developer tools and in the Storage tab, click Local Storage. RIght click on the entry and select Delete All.

**Comment by DarkAllMan** [comment]
I played around last night..
I ticked notification bar on and of… then it appeared again….

**Comment by davidlb** [comment]
I finally manage to reproduce this bug, I'll work on it this week.

**Comment by davidlb** [comment]
In fact, it was due to bad uservariables in Domoticz probably due to a previous buggy version of the theme.
Delete all theme-machinon* user variables in Domoticz (Setup / User Variables).
Clear storage in your local browser and it should be ok now.

**Comment by DarkAllMan** [comment]
This seems to have solved the issue :)

**Comment by DarkAllMan** [comment]
Sorry, after a refresh of the page, the logo disappeard again!

**Comment by davidlb** [comment]
I fixed few issues related to Firefox this morning, can you update to the latest beta branch and retry?
Can you send a screenshot/copy paste of Domoticz user variables?

**Comment by DarkAllMan** [comment]
Can you explain which console commands I need to give to change to the beta branche?
Or do you suggest to create a second theme for the beta?

**Comment by davidlb** [comment]
If you did a git clone to get the theme, just go to the theme folder and type:
git checkout beta
git pull

**Comment by DarkAllMan** [comment]
Branch 'beta' set up to track remote branch 'beta' from 'origin'.
Switched to a new branch 'beta'
git pull: Already up to date.

**Comment by davidlb** [comment]
Good, so you're already on the beta branch.
I've just found another bug on Firefox regarding the Reset Button, I'll ping you when I'm done.

**Comment by DarkAllMan** [comment]
First tests show the problem solved now, even after refreshing the pages.
User Variables show:
theme-machinon-custom (string): ["","","","",null,"",null]
theme-machinon-features (string): [15,29,33]

**Comment by davidlb** [comment]
Ok, thanks for your help! I keep you informed.

**Comment by davidlb** [comment]
Can you give it a try?

**Comment by DarkAllMan** [comment]
All seems to be ok.

**Comment by davidlb** [comment]
Oops wrong issue reopened, I close it
