### ISSUE TITLE
Big screens resolution issue

### ISSUE THREAD

**Issue by ebretteville** [EdddieN/machinon-domoticz_theme#268]
![2019-05-21 09_04_41-Domoticz Tours](https://user-images.githubusercontent.com/3687099/58096440-5a046a00-7bd5-11e9-98b1-ffe21e4493c7.png)
As you can see the space between the widgets is wrong on big resolution screen.
Thanks

**Comment by DewGew** [comment]
Looks like cache issue. What brower are you using?

**Comment by ebretteville** [comment]
Firefox

**Comment by davidlb** [comment]
I found several javascript errors in Firefox (it'ts probably related to your bug), I'll work on it this week.

**Comment by ebretteville** [comment]
Thx

**Comment by davidlb** [comment]
Any error message in the console?

**Comment by ebretteville** [comment]
js tab or css tab?

**Comment by davidlb** [comment]
js tab

**Comment by davidlb** [comment]
@ebretteville is it still the case? if not, can we close the issue?

**Comment by ebretteville** [comment]
Still the same, sorry can't send you the log, I tried but nothing really showed up

**Comment by davidlb** [comment]
Pleaase update to the last beta version and reset theme as I've fixed many issues with Firefox reseting/loading theme.

And tell me which options you enable in the theme to be sure I have the same.

**Comment by ebretteville** [comment]
Still on 
![2019-06-03 08_19_39-](https://user-images.githubusercontent.com/3687099/58786968-0ccac400-85e9-11e9-8560-b01cb0aeb1fa.png)
Version 1.9.1 on firefox ESR 60.7.0esr

**Comment by davidlb** [comment]
Thanks Etienne for all the details. Good news, I've been finally able to reproduce it and this happens only on Firefox ESR but not the latest Firefox version (67.0). I'm going to check if I can do something for it.
I keep you informed.

**Comment by ebretteville** [comment]
Great. I forgot to mention the esr specific version. My bad, but glad you were able to reproduce the bug.
Also (maybe esr specific) typing for example in blockly comments is really slow. If typing too quickly, some caracters aren't "captured". Anyway, really good job regarding this theme!

**Comment by davidlb** [comment]
It should be ok now :)
Regarding slowness of blockly, I won't be able to fix it, it could be related to Blockly or to Firefox.

**Comment by ebretteville** [comment]
Yes, good! Thx!
![2019-06-03 12_16_56-Domoticz Tours](https://user-images.githubusercontent.com/3687099/58794879-92567000-85f9-11e9-8707-8fe099fac926.png)
