### ISSUE TITLE
Floorplan visual bugs

### ISSUE THREAD

**Issue by chrislader** [EdddieN/machinon-domoticz_theme#269]
Floorplan stil has some 'old' original Domoticz UI elements.

Example:
- Dim slider

![image](https://user-images.githubusercontent.com/40333466/58129987-51368700-7c1b-11e9-8182-68ced09a7e3c.png)

**Comment by chrislader** [comment]
Found another thing here:
Selecting options from pulldown are full black, except mouseover

![image](https://user-images.githubusercontent.com/40333466/59548305-a67d6400-8f4d-11e9-9d44-96678c6f0129.png)

**Comment by EdddieN** [comment]
Hello,

Can I encourage everyone to continue the conversation in the domoticz repository:
https://github.com/domoticz/Machinon
