### ISSUE TITLE
[visual bug] Adding dummy device screen is too compact

### ISSUE THREAD

**Issue by chrislader** [EdddieN/machinon-domoticz_theme#273]
You need to scroll 1 line to see the type of device. Please add some heigth to the box :)

![image](https://user-images.githubusercontent.com/40333466/58746890-0f4fe100-8464-11e9-9610-57aa5bfffeb7.png)

**Comment by davidlb** [comment]
It's weird, I don't have the issue. What's your resolution?

![2019-06-03 13_32_13-Lyon – Brave](https://user-images.githubusercontent.com/12050155/58798745-b6b74a00-8603-11e9-94c8-7fa09898da0b.png)

**Comment by davidlb** [comment]
After some tests, I found it's related to the "Center popups" feature.

**Comment by davidlb** [comment]
Thanks for filling all these small bugs, we're on the way to perfection :)
