### ISSUE TITLE
[visual bug] buttons turn black after selecting line in hardware overview

### ISSUE THREAD

**Issue by chrislader** [EdddieN/machinon-domoticz_theme#274]
Again a small bug; but we are looking for perfection, right?

After selecting a device in the hardware overview, the button text turn black

![image](https://user-images.githubusercontent.com/40333466/58746921-605fd500-8464-11e9-9ca7-e494cfcc60d3.png)

Same goes for selecting a camera:

![image](https://user-images.githubusercontent.com/40333466/58746961-c2b8d580-8464-11e9-8ffe-c617c4b0b2e4.png)

**Comment by davidlb** [comment]
Good catch :)
