### ISSUE TITLE
[Improvment suggestion] Check available beta

### ISSUE THREAD

**Issue by ebretteville** [EdddieN/machinon-domoticz_theme#277]
If on beta channel, what about checking the latest beta available as the stable one. I'm on beta and in the notification bell I have reminder for 1.9.0 as I am on 1.9.1... ;-)

**Comment by DewGew** [comment]
https://github.com/EdddieN/machinon-domoticz_theme/commit/4a68edfd1c5f6f5ee688c35ab232ecb297c78983
