### ISSUE TITLE
Dimmer slider color

### ISSUE THREAD

**Issue by bizziebis** [EdddieN/machinon-domoticz_theme#279]
Would it be possible to show different color of slider when a dimmer device is on or off?

Now it always looks like the slider is greyed out. It would be nice if the slider could be coloured when the device is on, and grey when off. Just like the icon in front.

**Comment by davidlb** [comment]
Did you try the "Fade when device is off" option?
It gives this kind of result

![2019-07-25 15_31_35-Lyon – Brave](https://user-images.githubusercontent.com/12050155/61878791-f4449f00-aef1-11e9-8c3e-82b477610c47.png)
