### ISSUE TITLE
Slow and errors loading cameras on dashboard

### ISSUE THREAD

**Issue by EdddieN** [EdddieN/machinon-domoticz_theme#283]
Is anyone having this issue?
I notice that my Dashboard with all cameras enabled takes a long time to load, during this time the web interface becomes non responsive for a few seconds. 

I looked at network and I saw many failed calls to the snapshot. Is that normal? 
The curious thing is that the calls to the ones that are right are exactly the same ones that the one without a reply
![Screenshot 2019-06-14 at 20 44 32](https://user-images.githubusercontent.com/39434245/59534173-713d2b80-8ee5-11e9-909f-04c975d06b23.png)

**Comment by DewGew** [comment]
I noticed that too. Sometimes I reload the page.

**Comment by chrislader** [comment]
Same here, short freezes; very annoying

**Comment by davidlb** [comment]
I'll check it next week

**Comment by davidlb** [comment]
Is it OK now in beta? (fixed few weeks before)

**Comment by chrislader** [comment]
@davidlb Yes, at my side its working great. It was fixed with Ajax-fixes few weeks ago. I have no performance stutters anymore.

**Comment by davidlb** [comment]
@chrislader great, thanks for your feedback!
