### ISSUE TITLE
Device data timeout

### ISSUE THREAD

**Issue by Abbadon89** [EdddieN/machinon-domoticz_theme#29]
Hello, it will be good to add visible information that device is outdated. For example, like screenshot below different color of shadow. information about how long device is off also will be grat idea. 

![bez tytulu](https://user-images.githubusercontent.com/26330104/43201810-d604f780-9019-11e8-8829-7a3ce15d73af.png)

**Comment by landaisbenj** [comment]
Hello, it's in the wishlist.

**Comment by EdddieN** [comment]
This is the plan, to fade out devices when they are offline
![screen shot 2018-07-28 at 12 41 18](https://user-images.githubusercontent.com/39434245/43356170-8c6832c6-9263-11e8-9c04-2741a52b82ee.png)

**Comment by landaisbenj** [comment]
OMG find it and another stuff !!! I try to let you see.

**Comment by landaisbenj** [comment]
For status timeout, i think it's that:

.statusTimeout #itemtable {
    background-color: rgba(0,0,0,0.2);
}

![image](https://user-images.githubusercontent.com/32144431/43773485-2677a326-9a46-11e8-85aa-9c9dea00dda8.png)

**Comment by landaisbenj** [comment]
And i think i've find another cool stuff for low battery (omgomgomg):

`.statusLowBattery #itemtable  {
    animation-duration: 1200ms;
    animation-name: blink;
    animation-iteration-count: infinite;
    animation-direction: alternate;
    -webkit-animation:blink 1200ms infinite; /* Safari and Chrome */
}
@keyframes blink {
    from {
        background-color: rgba(255,0,0,0.2);
    }
    to {
        background-color: rgba(255,0,0,0);
    }
}
@-webkit-keyframes blink {
    from {
        background-color: rgba(0,0,0,0.2);
    }
    to {
        background-color: rgba(0,0,0,0);
    }`

**Comment by EdddieN** [comment]
RE time out =  I like it, I think with a bit of tweaking to fade out a bit the text it would look nice. 

RE low battery = I like it too, can the flashing be slowed down? That rate of refresh is a bit alarming, if it could be slowed down (a bit like a glow) and change the colour from red to say blue / green / or any other less alarming?

The red flashing is good and I think it can be used on other situations in the future too!

**Comment by landaisbenj** [comment]
Yes we can change the duration, and maybe we can make a pause between animation. I can make everything i think lol.

**Comment by landaisbenj** [comment]
Juste to play with possibilities : (it's kidding me xD)

![38215153_978478428990356_7713274519267311616_n](https://user-images.githubusercontent.com/32144431/43775074-a9c1d8a0-9a4b-11e8-8ac3-67bcc33c1cf5.gif)

**Comment by EdddieN** [comment]
Oh I didn't see this! Well.... why don't we let the user decide? DewGew has created a theme menu so it it would be nice if the user can select pulsing, not pulsing, tile colour, round colour...

I personally like this one: https://github.com/EdddieN/machinon-domoticz_theme/issues/29#issuecomment-411026272 but without the blinking and probably another colour than red. Red = alarm = warning... maybe something a bit grey or so

**Comment by landaisbenj** [comment]
Maybe. I think if you let users decide too often, you risk getting away from your basic theme.

**Comment by EdddieN** [comment]
then I would chose this one: https://github.com/EdddieN/machinon-domoticz_theme/issues/29#issuecomment-408601496

The colours are probably better suited for alerts, who knows a feature in the future?

**Comment by EdddieN** [comment]
That is really good! Let's leave it like that, we can always go back with tweaks. Fantastic work!!

![screen shot 2018-08-29 at 20 58 17](https://user-images.githubusercontent.com/39434245/44812164-6d4a5200-abce-11e8-8d29-eae8f225bc67.png)

**Comment by EdddieN** [comment]
Really nice about the border, can I suggest these changes?
![screen shot 2018-08-30 at 11 10 16](https://user-images.githubusercontent.com/39434245/44845517-a7a30600-ac45-11e8-96a2-3df30e033e2e.png)
Change the border to black instead of blue

also, to provide continuity with the design, I would add the glow/shadow as per example below:
![screen shot 2018-08-30 at 11 13 46](https://user-images.githubusercontent.com/39434245/44845582-d4571d80-ac45-11e8-9a97-13eb5245eadf.png)

**Comment by EdddieN** [comment]
@DewGew
