### ISSUE TITLE
1.10.1 but stuck in 1.9.9

### ISSUE THREAD

**Issue by ebretteville** [EdddieN/machinon-domoticz_theme#290]
As you see I have notifications that 1.10.1 is available but a git pull leaves me in 1.9.9

![2019-08-07 09_03_03-Domoticz Tours](https://user-images.githubusercontent.com/3687099/62601811-8be2be00-b8f2-11e9-9970-ddf89f207c37.png)
![2019-08-07 09_04_32-Domoticz Tours](https://user-images.githubusercontent.com/3687099/62601812-8be2be00-b8f2-11e9-9e39-584272f1c1d8.png)

**Comment by DewGew** [comment]
Click reset in theme setting and then clear localstorage

**Comment by ebretteville** [comment]
Ture, sorry for this dummy issue
