### ISSUE TITLE
Icons not showing

### ISSUE THREAD

**Issue by DewGew** [EdddieN/machinon-domoticz_theme#291]
Icons often is not showing. Tryed clear browser and app cache etc.

Browser console error:
```
VM1676 LightSwitches:1 
Failed to decode downloaded font: https://domoticz.com:443/acttheme/fonts/ionicons.woff2?v=4.6.2
```

![missingIcons](https://user-images.githubusercontent.com/28799807/63342792-b00bb980-c34c-11e9-9c69-47f2c1d769c5.png)

**Comment by davidlb** [comment]
I'm back from holidays, I'm going to check it in the next days

**Comment by davidlb** [comment]
DIdn't happen anymore since my fix
