### ISSUE TITLE
Features broken with Domoticz beta

### ISSUE THREAD

**Issue by davidlb** [EdddieN/machinon-domoticz_theme#294]
Some features (ie switches state) are broken with last Domoticz Beta versions. As Domoticz moved from ajax calls to websocket to get devices status, function $(document).ajaxSuccess(function (event, xhr, settings) in custom.js is not called anymore.

https://github.com/EdddieN/machinon-domoticz_theme/blob/184fc3c43d93c05fd1a23e951a1898090a260457/custom.js#L175-L227

**Comment by davidlb** [comment]
For the moment, I just found the switch feature broken.
I started to create a branch to manage websocket.

**Comment by davidlb** [comment]
And I guess notifications are broken too (I don't use them)

**Comment by DewGew** [comment]
My notifications work

**Comment by DewGew** [comment]
Now I get it. Its not custom functions is not updating. Did you find any solution?

**Comment by davidlb** [comment]
We need to catch update from the websocket but it needs rewrite of several functions. I think the better will be to create a new branch

**Comment by DewGew** [comment]
Sure use this one: https://github.com/EdddieN/machinon-domoticz_theme/tree/websocket

**Comment by DewGew** [comment]
Getting anywere with this? I dont have any clue about websockets..

**Comment by davidlb** [comment]
Not much, switches are more or less working :/

**Comment by davidlb** [comment]
@EdddieN @DewGew do we really need big switches? It's a ugly hack in JS & CSS just to imitate the icon behaviour and I don't know how to make it working properly with Domoticz beta.

**Comment by EdddieN** [comment]
No we don't, which switches? let me know what you mean and we probably can change  it to be easier to maintain.

**Comment by davidlb** [comment]
![image](https://user-images.githubusercontent.com/12050155/67221296-84c84800-f42b-11e9-83fc-120eead8336a.png)

These switches

**Comment by DewGew** [comment]
I don’t use them. But I think then are quite handy🤔

**Comment by davidlb** [comment]
@DewGew it should have been fixed few hours ago with commit 3bf1663be4f984425c3b927018bc15534e13e3ec

**Comment by EdddieN** [comment]
the original design did not have them. That was done becasue back then we did not know how to make the buttons on or faded out. Maybe we could do it now? A bit like Homekit?

**Comment by davidlb** [comment]
I'm done with websocket changes (major refactoring). Can you test the branch?
I didn't test the rewrite with previous version of domoticz (without websocket) but it should also work.

Note: for the moment: switch are only displayed for on/off switch.

**Comment by davidlb** [comment]
Merged into beta
