### ISSUE TITLE
menu bar color in dark theme

### ISSUE THREAD

**Issue by Lyr3x** [EdddieN/machinon-domoticz_theme#298]
Personally i am not a big fan of the pure black menu bar in the dark theme because it is a very hard color break. The rest of the color picks are just awesome IMHO. 

However i want to bring up a suggestion for a different color:
![image](https://user-images.githubusercontent.com/6078365/65372071-6d9b0c80-dc6b-11e9-9105-bee8e95a4059.png)
This is hexcode: #232324

For a direct comparison, here the original:
![image](https://user-images.githubusercontent.com/6078365/65372083-a33ff580-dc6b-11e9-8c38-b2baaca092cb.png)

What do you guys think?

**Comment by davidlb** [comment]
Hello,
Yes, you're right, it's better with dark grey. I changed it in beta.
Thanks for your remark!
