### ISSUE TITLE
Long text on text device create an overview

### ISSUE THREAD

**Issue by landaisbenj** [EdddieN/machinon-domoticz_theme#30]
We can make a automatic scroll to fix that.

**Comment by EdddieN** [comment]
Scrolling would be nice, it would bring a feeling of alive system

**Comment by landaisbenj** [comment]
Yes!!! I think about it too. Some mini feature can bring the project more alive like this or with some gif/icon but more hungry too 😒

**Comment by poudenes** [comment]
With latest beta: bbd765f..c2056b9 text is still going outside the div container
