### ISSUE TITLE
Code Issues reported by Deepscan.io

### ISSUE THREAD

**Issue by davidlb** [EdddieN/machinon-domoticz_theme#303]
I setup Deepscan on the git repo to report code issues.
Dashboard is here: https://deepscan.io/dashboard#view=project&tid=5627&pid=7466&bid=76214

**Comment by davidlb** [comment]
@EdddieN it would be better if you could run deepscan.io on this repo (rather than my fork repo)

**Comment by EdddieN** [comment]
This: https://deepscan.io/dashboard/#view=project&tid=5668&pid=7507&bid=77435&subview=overview

**Comment by EdddieN** [comment]
How do I make you collaborators there? or there's no need?

**Comment by DewGew** [comment]
> How do I make you collaborators there? or there's no need?

Maybe try  'Create Team'. You find that in the droplist with your username

**Comment by davidlb** [comment]
@EdddieN thanks, can you also scan the beta branch?

**Comment by EdddieN** [comment]
> @EdddieN thanks, can you also scan the beta branch?

done, also have invited @DewGew but cannot see email to invite you @davidlb

**Comment by davidlb** [comment]
@EdddieN  my email address is david [-at-] trucs.org
