### ISSUE TITLE
Evohome set point temperature dark theme

### ISSUE THREAD

**Issue by EdddieN** [EdddieN/machinon-domoticz_theme#304]
See attached, when setting Evohome temperature (Temperature tab), the screen appears white on the dark theme.
![Screenshot 2019-10-12 at 11 42 33](https://user-images.githubusercontent.com/39434245/66700156-7ff5ec80-ece5-11e9-86d6-579a5c1ba004.png)

**Comment by BOverdevest** [comment]
This also happens when adding a new virtual sensor to a Dummy hardware.
The text is white on a light grey back ground.
<img width="700" alt="Schermafbeelding 2019-10-13 om 16 43 04" src="https://user-images.githubusercontent.com/37892181/66717376-9a5cc280-edd8-11e9-93c7-0fc3f931202f.png">
