### ISSUE TITLE
Missing icon files

### ISSUE THREAD

**Issue by vampywiz17** [EdddieN/machinon-domoticz_theme#306]
Hello there,

I found some missing icon files:

Custom (the Custom_on and Custom_off is exist)

Wallsocket (the Wallsocket_on and Wallsocket_off is exist)

humidity, if it not come together with temperature. (the temp+humidity is good.)

![image](https://user-images.githubusercontent.com/14281430/66829465-b89afd80-ef53-11e9-95ba-91b972682640.png)

**Comment by vampywiz17** [comment]
Added pull request.

https://github.com/EdddieN/machinon-domoticz_theme/pull/307

**Comment by davidlb** [comment]
Thanks @vampywiz17 , we'll take a look at it after fixing websocket problems introduced in domoticz beta

**Comment by davidlb** [comment]
Thanks for your fix!
