### ISSUE TITLE
PS4 (or game console) icon

### ISSUE THREAD

**Issue by BOverdevest** [EdddieN/machinon-domoticz_theme#308]
Hello

Would it be possible to add a Game console icon>
Like this on?
[https://opengameart.org/content/ps4-controller-icon](https://opengameart.org/content/ps4-controller-icon)

Or can I add it myself via pull request? Any style rules to follow?
Bart

**Comment by davidlb** [comment]
You can easily add your own icons in Domoticz.
Using this website, it will generate a package and then in Domoticz go to Parameters > Custom Icons > Upload button
And then on your switch settings, you will be able to select it.
