### ISSUE TITLE
xMasEdition2019 is out!

### ISSUE THREAD

**Issue by DewGew** [EdddieN/machinon-domoticz_theme#310]
![xMasEdition2019](https://user-images.githubusercontent.com/28799807/69061696-f50dbd80-0a19-11ea-9bf2-544502f8cf6c.png)

Update machinon install (keeps your settings):
`cd domoticz/www/styles/Machinon
git pull
git checkout xMasEdition2019`

New install:
`cd domoticz/www/styles
git clone https://github.com/EdddieN/machinon-domoticz_theme Machinon
cd Machinon
git checkout xMasEdition2019`

Go back to normal:
`cd domoticz/styles/Machinon
git checkout master (or beta)`

**Comment by EdddieN** [comment]
That put a smile on my face!

**Comment by josemi73** [comment]
Do you plan to implement/merge xMasEdition2019 in beta branch?
