### ISSUE TITLE
Switch instead of text visual bug

### ISSUE THREAD

**Issue by niawag** [EdddieN/machinon-domoticz_theme#316]
Hi, I think I'm facing a small visual bug. I turned on the option "Switch instead of text" in the Devices section of theme settings and I'm getting that for Selector Switches:
![image](https://user-images.githubusercontent.com/5684014/72712342-21a19b00-3b6b-11ea-897f-d6b34235b7ae.png)
--> you can see the switch on top of the selector switch

I cleared cache, appcache, browser storage while resetting theme, same problem.

This was working in v1.10.2 and the bug appeared in 1.12 and is still there in 1.14 (my current version)

**Comment by davidlb** [comment]
Do you still have it in the last version?
If yes, whats' your domoticz version, machinon theme version and browser?

**Comment by niawag** [comment]
Hi and thanks for your help.

I updated to v15 and it's still happening, I've tested with Chrome (x64 - 79.0.3945.130) and Edge (44.17763.831.0) and the same is happening.
Domoticz version : 
Version: 4.10717
Build Hash: b38b49e5
Compile Date: 2019-05-09 13:04:08
dzVents Version: 2.4.19
Python Version: 3.7.3 (default, Apr 3 2019, 05:39:12) [GCC 8.2.0]

I've done the steps described in the readme to make sure the update is applied, the theme version is shown in the settings (v15) so everything should be ok, I also restarted Domoticz, just in case! I've also checked that there was no domoticz.js.gz 

If you need something to debug it, feel free to ask!

Thanks for your help and for your awesome theme!

**Comment by davidlb** [comment]
Thanks, I have been able to reproduce it and fix it :)

**Comment by niawag** [comment]
Great! Thanks a lot!
