### ISSUE TITLE
Changing a selector switch sends multiple requests from mobile device

### ISSUE THREAD

**Issue by blazoncek** [EdddieN/machinon-domoticz_theme#317]
I have a selector type switch with 25 possible selections in Domoticz and when I change the selection on mobile device (on a Dashboard at least) it sends multiple requests to Domoticz.
Until recent updates this worked normally, when changed it only sent one request.

I am observing this behavior via MQTT where I see multiple domoticz/out messages with the same payload for the switch (more than 60 sometimes) after the change on mobile device Dashboard.

The issue does not appear on the desktop though.

Mobile device: iOS 12.3.1 (Safari & Firefox)

**Comment by davidlb** [comment]
I have been able to reproduce it and you're right, it fires 5 times when you change the selection on mobile devices. I'm going to work on it.
