### ISSUE TITLE
Settings menu disappears

### ISSUE THREAD

**Issue by felix63** [EdddieN/machinon-domoticz_theme#318]
Since installing 1.14 the whole Settings menu disappears when selecting the option 'Machinon Settings Menu'. Without this option active settings menu is there. Cleared cache and restarted domoticz but problem stays.

Problem seems to be Firefox & Safari only. In Chrome it works as before.

**Comment by mattx38** [comment]
Same issue. How can we find the original theme ??

**Comment by chrislader** [comment]
Got the same issue. Will monitor this thread.

**Comment by davidlb** [comment]
@mattx38 to change theme, add/change the url to #/Setup

**Comment by davidlb** [comment]
I' m running Firefox 72.0.2 (win 64) and I don't have the issue.
I need your help, can you give me more details: browser version, when does it happen, any error in the browser console and the options you enable in the theme. Does a refresh of the page (F5) make the menu available ?

**Comment by felix63** [comment]
<img width="467" alt="Schermafbeelding 2020-01-29 om 10 34 15" src="https://user-images.githubusercontent.com/16501940/73636363-fbe5bd00-4665-11ea-9a51-ec76a6cad0dd.png">
<img width="467" alt="Schermafbeelding 2020-01-29 om 10 33 45" src="https://user-images.githubusercontent.com/16501940/73636364-fbe5bd00-4665-11ea-870b-672c9969078f.png">

I have included two screen prints showing what happens. Refresh doesn't help neither does clearing the cache.

I am using Safari Version 13.0.5 (14608.5.12) on Mac 10.14.6

The webinfo shows the following warnings and errors:
<img width="1265" alt="Schermafbeelding 2020-02-03 om 09 23 13" src="https://user-images.githubusercontent.com/16501940/73636825-1d937400-4667-11ea-8db5-5b1dfd3ad02f.png">
<img width="1265" alt="Schermafbeelding 2020-02-03 om 09 23 00" src="https://user-images.githubusercontent.com/16501940/73636826-1d937400-4667-11ea-8373-e4bdccb1a3d8.png">

**Comment by davidlb** [comment]
thanks for all these details! I'll work on it but I have an idea on what could be wrong.

**Comment by felix63** [comment]
Let me know if I can help!

**Comment by davidlb** [comment]
Can you update to the last version in beta branch? I reverted one commit that could be the origin of the problem.

**Comment by davidlb** [comment]
Issue is still here, I have it on my mobile, I'll try to find a fix in the next days

**Comment by Kratax** [comment]
Just to add (after posting to forum) - using Firefox latest version, latest version of Domoticz beta, the following in the console of the browser...


This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. 10.1.14.39:8080
Synchronní XMLHttpRequest v hlavním vláknu je zastaralý z důvodu jeho špatného vlivu na uživatelský prožitek. Pro více informací si přečtěte http://xhr.spec.whatwg.org/ jquery-3.4.1.min.js:2:80629
Machinon - theme settings was already found in the browser. 10.1.14.39:8080:242:21
Machinon - found theme feature settings in Domoticz database (user variable Idx: 12) 10.1.14.39:8080:305:33
Machinon - found theme feature settings in Domoticz database (user variable Idx: 13) 10.1.14.39:8080:311:33
TypeError: generate_noty is not a function
10.1.14.39:8080:175:15
$tooltip is now deprecated. Use $uibTooltip instead. angular.min.js:124:532
Na nezabezpečené stránce (http://) se nachází pole pro zadání hesla. Jedná se o bezpečnostní riziko, v rámci kterého může dojít k odcizení přihlašovacích údajů.
10.1.14.39:8080

​

**Comment by davidlb** [comment]
I reworked the management of the setting menu, can you give it a try? (beta branch / latest version 1.15.2)

**Comment by felix63** [comment]
That seems to do the trick. Great work!

**Comment by josemi73** [comment]
Thank you
