### ISSUE TITLE
Minor visual bug in DzVents scripts screen

### ISSUE THREAD

**Issue by chrislader** [EdddieN/machinon-domoticz_theme#320]
Text should be Blue (not white).

![image](https://user-images.githubusercontent.com/40333466/73133229-f7962000-4025-11ea-96c7-17004b15d408.png)

**Comment by davidlb** [comment]
What's your version of Domotics and Machnin theme?
I don't have the issue (domoticz beta / machinon beta)

![2020-02-03 14_07_20-Slack](https://user-images.githubusercontent.com/12050155/73655532-8fcb7f00-468e-11ea-8bb9-9cbd8edf339d.png)
