### ISSUE TITLE
Switch Status not updated

### ISSUE THREAD

**Issue by DarkAllMan** [EdddieN/machinon-domoticz_theme#325]
I'm not sure this is a theme or a domoticz issue. But when I turn on a switch, the switch status stays off until I refresh the page. In the past it would update the switch status without refreshing.

**Comment by davidlb** [comment]
What is your domoticz version (stable / beta / version number)?

**Comment by DarkAllMan** [comment]
Beta Version: 4.11690

**Comment by DarkAllMan** [comment]
After analyzing, it seems it's related to 2 things. I migrated to Domoticz behind NginX Reverse Proxy, and Domoticz now uses WSS instead of Ajax. Don't think it's related to Machinon.

**Comment by DarkAllMan** [comment]
I confirm that by adjusting the NginX settings, my issue is solved!
