### ISSUE TITLE
New design side menu suggestion

### ISSUE THREAD

**Issue by chrislader** [EdddieN/machinon-domoticz_theme#326]
Hi David,

For a while I am using my own modification of the side menu (because I think the blue one is not nice). Although it's a taste thing; i'd like to share my design, maybe more people like it?

My design:
![image](https://user-images.githubusercontent.com/40333466/74607185-e2695a00-50d6-11ea-84ce-0e1f5d029982.png)

I have decreased the width to 45 px (to fit the icons better) and made the panel transparant for 90%. It's give it a way more subtle look.

![image](https://user-images.githubusercontent.com/40333466/74607168-b948c980-50d6-11ea-9020-186fe2b84824.png)
sidemenu.css, line 25 -> 45px

![image](https://user-images.githubusercontent.com/40333466/74607141-67a03f00-50d6-11ea-9191-33f082466a7d.png)
smaller padding; 5px
transparant color style
white subtle lines 

What do you guys think?

**Comment by EdddieN** [comment]
I like it! Anythign that makes thing simpler... is good.

**Comment by davidlb** [comment]
I like it too, I'll do it in the next weeks

**Comment by EdddieN** [comment]
Hello,

Can I encourage everyone to continue the conversation in the domoticz repository:
https://github.com/domoticz/Machinon

**Comment by davidlb** [comment]
Thanks, it's much better now and less code!
