### ISSUE TITLE
Dark theme improvement suggestion

### ISSUE THREAD

**Issue by chrislader** [EdddieN/machinon-domoticz_theme#328]
Hi David, 

While your at it, I might share 2 simple improvements in the UI for Dark mode, which improve the overal feel I think;

Sensor value = white (big text)
Slider is light grey, same grey as updated last time text

![image](https://user-images.githubusercontent.com/40333466/75120257-82e8ec80-568a-11ea-952d-a4bedab0013c.png)

Alternatively: slide in same color as background (= as is)
![image](https://user-images.githubusercontent.com/40333466/75121007-68197680-5690-11ea-97fc-db557d6fa92a.png)

![image](https://user-images.githubusercontent.com/40333466/75120279-b75ca880-568a-11ea-9d64-e9e8e97b6982.png)

I can add the Raspberry icon to the icon set as well, if you like. This gives the pimonitor plugin a more obvious icon instead of custom sensor (=default)

Again, just my opinion. Maybe you like it. Let me know. :)

**Comment by EdddieN** [comment]
Hello,

Can I encourage everyone to continue the conversation in the domoticz repository:
https://github.com/domoticz/Machinon

**Comment by davidlb** [comment]
Thanks for your suggestions, I took them in account in commit domoticz/Machinon@fbd4664e8405d173bf2cb75cb9d442aa54c805ac
