### ISSUE TITLE
[Visual Bugs] some small visual thingies found

### ISSUE THREAD

**Issue by chrislader** [EdddieN/machinon-domoticz_theme#330]
Hi there,

Again in our pursuit for perfection, just pointing out some things:

Tested at v4.11775
Machinon: v1.15.2

![image](https://user-images.githubusercontent.com/40333466/75971979-da7d2880-5ed2-11ea-8ed1-56d67a83865a.png)
Number at updating; should be dark gray I think

![image](https://user-images.githubusercontent.com/40333466/75972032-f41e7000-5ed2-11ea-9be7-873b88a319d8.png)
Custom graph text is white at temperature screen

![image](https://user-images.githubusercontent.com/40333466/75972198-495a8180-5ed3-11ea-86cb-62605493af04.png)
Not sure why, but there seem to be an empty field at notifications (could be caused by domoticz itself and not Machinon UI)

**Comment by EdddieN** [comment]
Hello,

Can I encourage everyone to continue the conversation in the domoticz repository:
https://github.com/domoticz/Machinon

**Comment by davidlb** [comment]
Sorry, I checked but I cannot fix these 2 visuals bugs, they are generated by domoticz.
