### ISSUE TITLE
webroot

### ISSUE THREAD

**Issue by dbrb2** [EdddieN/machinon-domoticz_theme#332]
Unsure if this is an issue with the theme or with domoticz itself, but if the webroot is set::

domoticz -daemon -www 8080 -webroot home

Then a number of theme features stop working. 

On investigation, if I set webroot to "home" then I can access domoticz at: 
http://<ip>:8080/home/

However, I can see failed calls being made by the theme to: 

http://<ip>:8080/acttheme/js/settings_page.js?Machinon

rather than: 

http://<ip>:8080/home/acttheme/js/settings_page.js?Machinon

**Comment by EdddieN** [comment]
it may be some non absoluts calls in the code as you point, I have seen this happenign before. 

Are you accessing your installation via a remote seerver like my.domoticz?

**Comment by davidlb** [comment]
Hmm, it looks like a bug in our theme.
I'll do some tests in the next days to fix the error.
