### ISSUE TITLE
Difference between default and active branch

### ISSUE THREAD

**Issue by landaisbenj** [EdddieN/machinon-domoticz_theme#39]
Do you know why we have this ? and if it's better ? 

![image](https://user-images.githubusercontent.com/32144431/44715246-91ffd600-aab7-11e8-827b-8a07f7060cbe.png)

**Comment by EdddieN** [comment]
I have no idea... I just deleted them. 

I think it was when I was trying to add the GPL licence at the beginning and was getting used to Github, well still I'lm LOL!
