### ISSUE TITLE
Absolute file path settings file 

### ISSUE THREAD

**Issue by EdddieN** [EdddieN/machinon-domoticz_theme#43]
See attached, if accessing Domoticz via its remote proxy, it fails to load the settings styles
![screen shot 2018-08-29 at 20 51 31](https://user-images.githubusercontent.com/39434245/44811803-78e94900-abcd-11e8-8da0-cef55306b952.png)

I think the references to the files are absolutes instead of relatives and it fails to load when used under a different URL like my.domoticz

**Comment by DewGew** [comment]
Do you running latest from github? I changed the handling of settings.css

**Comment by EdddieN** [comment]
yes, try it, I think is the file paths probably are not relative

**Comment by DewGew** [comment]
Try to add import into your custom.css e.g:
`@import url("/css/settings.css"); /* css file for Settings.html. */`

**Comment by DewGew** [comment]
Dont Know much about proxy. I don’t Know how to configure.

**Comment by EdddieN** [comment]
Register an account here http://my.domoticz.com/ and try it. This is making a reverse proxy to your system without opening a firewall hole in your router. You'll have to setup the My Domoticz part too on your system

**Comment by DewGew** [comment]
#48

**Comment by EdddieN** [comment]
thank you!
