### ISSUE TITLE
Utility tab colour border

### ISSUE THREAD

**Issue by EdddieN** [EdddieN/machinon-domoticz_theme#51]
See attached, this device is not offline but shows as red, when I hoover over, the border becomes blue as standard. Is it possible that the red comes from the value of the CO2 sensor?
![screen shot 2018-08-31 at 17 15 08](https://user-images.githubusercontent.com/39434245/44923954-b5d64c80-ad41-11e8-820f-e4738a4d8b29.png)

**Comment by DewGew** [comment]
It comes from Low battary. If the device dont have any battery try to reboot Domoticz.

**Comment by EdddieN** [comment]
No it is correct, it is a battery one and indeed it has a low battery. However I just a conflict on information:

offline = faded out+ red vs low battery = red  => I think this could be confusing for users. What do you think? Is it worth playing with design? I'm not sure if Domoticz allows for an icon to be added on the tile, I would say battery low should have a icon or so instead the red line? Just a thought.

**Comment by EdddieN** [comment]
Ok, I'm closing this. I think I need to unify the different basic options for the boxes. I think for the users that are not that familiar, all this colours may be confusing. Leave it with me, I'll update the colour codes

**Comment by DewGew** [comment]
Better with yellow?

**Comment by EdddieN** [comment]
I'll upload a few ideas to the forum. I like to keep separated Online from Offline and the all of the other signals that Domoticz gives, like battery, high level, etc...
