### ISSUE TITLE
Theme settings tab not accessible via mobile

### ISSUE THREAD

**Issue by EdddieN** [EdddieN/machinon-domoticz_theme#52]
It seems the layout is a bit messed up and it is impossible to tap on Theme settings.
![img_1176](https://user-images.githubusercontent.com/39434245/44924084-22e9e200-ad42-11e8-89ee-0c30346837f9.jpg)

**Comment by EdddieN** [comment]
Can anyone access the theme settings using mobile phone, or Safari on iphone?

**Comment by EdddieN** [comment]
has anyone tried this? I cannot click on the Theme setting under Safari or Chrome on any mobile device.

**Comment by DewGew** [comment]
Its not working for me either. I cant find any solution for this..

**Comment by DewGew** [comment]
Its working on samsung andorid phone ..

**Comment by EdddieN** [comment]
The curious thing is that in chrome emulating iphone it works fine... probably a miss alignment somewhere... The mobile access probably needs at some point some re-design/work.

**Comment by EdddieN** [comment]
Tested on Ipad too, same issue, all the tabs are accessible except the Theme one

**Comment by ivooovi** [comment]
Tried it again this morning on both ipad and iphone no luck so can't access the specific machinon theme settings.

**Comment by DewGew** [comment]
I found a solution #103

**Comment by ivooovi** [comment]
Thanks ! it works indeed
