### ISSUE TITLE
Huge domoticz icon when selecting mobile/dashboard

### ISSUE THREAD

**Issue by sweetpants** [EdddieN/machinon-domoticz_theme#55]
When I selecting Mobile/dashboard, there is a huge domoticz ICON on the screen of my Samsung

![mach_icon](https://user-images.githubusercontent.com/23421160/44955150-20f16180-aeaf-11e8-9714-bb6d948789c4.png)

**Comment by sweetpants** [comment]
BTWm same behaviour when selecting Mobile/Mobile

**Comment by DewGew** [comment]
Cache issue..

**Comment by sweetpants** [comment]
Oeps, you where right
