### ISSUE TITLE
Scenes icons mixed

### ISSUE THREAD

**Issue by EdddieN** [EdddieN/machinon-domoticz_theme#59]
See attached, before they were either on or off. 

An Scene may not need the switch icon but it is nice to see there as a reference? or should just not be there? 
![screen shot 2018-09-03 at 20 18 49](https://user-images.githubusercontent.com/39434245/44999635-baf00180-afb6-11e8-8938-eed6139be651.png)

**Comment by landaisbenj** [comment]
i Think should not be there. Because i think we can not do off...

**Comment by EdddieN** [comment]
Fixed on last update
