### ISSUE TITLE
Inconsistent font on machinon downloaded/installed today

### ISSUE THREAD

**Issue by heggink** [EdddieN/machinon-domoticz_theme#60]
Some of the fonts are in Times new roman where everything else is different. No idea what cases the TNR font but probably beter if it looks the same as the rest ;-).
Fonts concerned:
- device names
- log headers
- groups on the top settings page
- fonts on the detailed settings page
some examples attached.

Android looks all good, both windoze and linux don't (Edge, Firefox, Chrome, alle with cleared cache/history/..).

H
![example 3](https://user-images.githubusercontent.com/3987735/45000856-99981100-afc8-11e8-8d45-2339bb91316a.jpg)
![example 2](https://user-images.githubusercontent.com/3987735/45000857-99981100-afc8-11e8-8027-9a4b9a18ee42.jpg)
![example2](https://user-images.githubusercontent.com/3987735/45000858-99981100-afc8-11e8-8dd0-d06ccc8b7a92.jpg)
![screenshot](https://user-images.githubusercontent.com/3987735/45000859-99981100-afc8-11e8-8797-58c2b881e82a.jpg)

**Comment by EdddieN** [comment]
Check last pull, it is fixed

**Comment by heggink** [comment]
Brill! Confirmed and thx.
