### ISSUE TITLE
IE and Edge alignment issues

### ISSUE THREAD

**Issue by heggink** [EdddieN/machinon-domoticz_theme#63]
In both Edge and IE, the alignment looks a bit off, agree? 3 wide is IE at 200%, 2 wide is edge at 100%. Both on a surface pro 4.

![sample2](https://user-images.githubusercontent.com/3987735/45028488-8aa37400-b045-11e8-82da-52c45034aee4.JPG)
![sample1](https://user-images.githubusercontent.com/3987735/45028492-8d9e6480-b045-11e8-86e8-86951fbf5a61.jpg)

**Comment by landaisbenj** [comment]
People still use ie ??? xD i'm kidding

**Comment by heggink** [comment]
Use? No but I noticed that it did not look OK on Edge so decided to try IE as well which was (as to be expected) similar. In some cases I even need IE since security for sharepoint mounted drives only gets updated through IE, not edge (when you open them in windoze explorer). Bizarre but true.

**Comment by EdddieN** [comment]
I don't have access to a Windows machine but I'll see what I can do. 
When you say 200%, do you mean zoom? that changes to 3 tiles at 200% but at 100% uses 2?

**Comment by heggink** [comment]
@EdddieN nvm the zoom as the surface pro (or windoze for that matter) is rather iffy switching backwards/forwards between its own screen and an external monitor with a lower resolution. But essentially yeah!

**Comment by EdddieN** [comment]
Merging to this thread, these are ver similar:
https://github.com/EdddieN/machinon-domoticz_theme/issues/31
