### ISSUE TITLE
Dashboard messed up after latest commit #1533a38

### ISSUE THREAD

**Issue by sweetpants** [EdddieN/machinon-domoticz_theme#64]
After last update (commit #1533a38) when you retunr to your dashboard, the screen got messed up
![image](https://user-images.githubusercontent.com/23421160/45028698-57adb000-b046-11e8-9dea-559733c56bb1.png)

After a refresh all is well again

Also it seems that since this commit all devices are centered also giving a messys screen
![image](https://user-images.githubusercontent.com/23421160/45028694-53819280-b046-11e8-8a4b-62260448270a.png)

**Comment by landaisbenj** [comment]
ok thanks for your feedback

**Comment by landaisbenj** [comment]
Can't reproduce :/ but i think it's the same problem what i have for last tile. I go back on this.

**Comment by EdddieN** [comment]
I don't have that issue, can you confirm browser you are using @sweetpants

**Comment by landaisbenj** [comment]
@DewGew find mobil app seems to be got the same problem...

**Comment by landaisbenj** [comment]
@sweetpants do you know how to inspect main-view element in html code ?

**Comment by EdddieN** [comment]
Ok, I think I found how to reproduce this. I had the "normal" dashboard and on my mobile device it looked like this:
![img_1210](https://user-images.githubusercontent.com/39434245/45110255-abe58c80-b139-11e8-8e4e-7ab9b09e4639.jpg)

Then I changed the Dashboard setting to "compact" and this is what I got on my desktop browser:
![screen shot 2018-09-05 at 18 30 56](https://user-images.githubusercontent.com/39434245/45110331-dafbfe00-b139-11e8-99a1-66efa51d4cb9.png)

when I switch back to normal then is fine. Maybe the compact is creating conflict?

**Comment by sweetpants** [comment]
Sorry guys, I was away today.

@EdddieN, 
"can you confirm browser you are using", I'm using Chrome on my desktop and mobile
"do you know how to inspect main-view element in html code ?", no i don't

I can reproduce this when switching from dash to switch and back to dash

**Comment by EdddieN** [comment]
Can you confirm and try changing dashboard view under settings?

Also make sure you clear cache and app cache: chrome://appcache-internals/# you'll see the IP of your domoticz install there, just remove it (make sure your domoticz tab is closed)

**Comment by EdddieN** [comment]
@sweetpants are you still having issues with the last update?

**Comment by sweetpants** [comment]
Just updated to latest version and looking much better.
BTW, love the way you can show the logs now directly instead of via a menu, thanks for the support

**Comment by EdddieN** [comment]
See this commit: https://github.com/EdddieN/machinon-domoticz_theme/pull/84 ok for you?
