### ISSUE TITLE
Edit tiles and icons

### ISSUE THREAD

**Issue by EdddieN** [EdddieN/machinon-domoticz_theme#67]
Switch from this:
![screen shot 2018-09-05 at 18 33 33](https://user-images.githubusercontent.com/39434245/45110480-52319200-b13a-11e8-8301-edfaa67bcfbd.png)

to this:
![screen shot 2018-09-05 at 18 32 49](https://user-images.githubusercontent.com/39434245/45110484-565daf80-b13a-11e8-98ac-1b14119b6075.png)

**Comment by EdddieN** [comment]
Notice the menu 3 dots it is a bit less in the way of the switch icon.
Also the access to log and timers is quicker. 
Timer should be coloured if timers are enabled/active?

**Comment by landaisbenj** [comment]
A suggest for icon log. We don't have to make them if we make last seen link for log... On click by last Seen: 2018-04-15 it open log page...

**Comment by EdddieN** [comment]
Do you mean you prefer to have the small bar icon?

The last seen text it is an option now under theme settings, so we may risk disabling log by removing it from the theme settings.

**Comment by landaisbenj** [comment]
Yes you're right. In first way yes i prefer icon bar like apple or other... I think less but more facility is good. Icon may be cool. Lastseen is an option just for dashboard. But we can't change this untile change other things. I don't speak about add log icon. I speak about href on last seen. like this:
![image](https://user-images.githubusercontent.com/32144431/45158776-523a9c00-b1e5-11e8-9dec-a4e6502bea67.png)
if you clik on link you get log... Like this you can get free space from log icon

**Comment by DewGew** [comment]
I prefer the icon. Looks better and easier to find for new users.

**Comment by DewGew** [comment]
#82
