### ISSUE TITLE
Update icons screen

### ISSUE THREAD

**Issue by EdddieN** [EdddieN/machinon-domoticz_theme#70]
See attached, update from
![screen shot 2018-09-05 at 18 39 27](https://user-images.githubusercontent.com/39434245/45110762-164afc80-b13b-11e8-9087-27a70397effb.png)
to
![screen shot 2018-09-05 at 18 40 04](https://user-images.githubusercontent.com/39434245/45110775-22cf5500-b13b-11e8-87ea-d8fbe0f017f2.png)

**Comment by EdddieN** [comment]
I don't think the screen needs to be identical but could do with a bit of styling?

**Comment by EdddieN** [comment]
Closing?

**Comment by davidlb** [comment]
@DewGew

**Comment by DewGew** [comment]
This i fixed..
