### ISSUE TITLE
Update icons settings screen

### ISSUE THREAD

**Issue by EdddieN** [EdddieN/machinon-domoticz_theme#71]
See featured requested a while back about more colours on the settings screen as it was a bit hard to quickly recognise options. This is what looks now:
![screen shot 2018-09-05 at 18 41 34](https://user-images.githubusercontent.com/39434245/45110893-6fb32b80-b13b-11e8-9a90-66df4a1a8fd7.png)

This is what it is proposed:
![screen shot 2018-09-05 at 18 41 26](https://user-images.githubusercontent.com/39434245/45110901-76da3980-b13b-11e8-85fe-5c929ca67a8d.png)

These are in Zeplin

**Comment by DewGew** [comment]
I look into this...

**Comment by DewGew** [comment]
Changes fixed  in pull reguest #78
