### ISSUE TITLE
sub navigation weather and others

### ISSUE THREAD

**Issue by EdddieN** [EdddieN/machinon-domoticz_theme#72]
Is it worth moving from this:
![screen shot 2018-09-05 at 18 43 31](https://user-images.githubusercontent.com/39434245/45110976-ab4df580-b13b-11e8-8e88-6213fde1ceaf.png)

to this?
![screen shot 2018-09-05 at 18 43 39](https://user-images.githubusercontent.com/39434245/45110985-b0ab4000-b13b-11e8-9dbb-5b213e1d186e.png)

**Comment by EdddieN** [comment]
Same with other screens like temperature
![screen shot 2018-09-05 at 18 44 40](https://user-images.githubusercontent.com/39434245/45111029-cae51e00-b13b-11e8-82be-a256b9642ff2.png)

**Comment by landaisbenj** [comment]
Yes we can.  We need to refund totaly tile with 
https://github.com/EdddieN/machinon-domoticz_theme/issues/67 and flex do the work i think

**Comment by EdddieN** [comment]
Sorry I think I was not clear, ignoring the tiles. I think the tiles I designed are a bit too complex so I wouldn't make them a priority for now, only parts of it like the small icons. Of course if you can replicate the tile even better! 

What I meant is this:
![screen shot 2018-09-06 at 09 39 58](https://user-images.githubusercontent.com/39434245/45145625-02de7680-b1b9-11e8-9d4b-934ad8ce664a.png)

**Comment by landaisbenj** [comment]
Hu ok, Nice. We must a real block for nav and title content with sun clock. Isn't it in original html.

**Comment by EdddieN** [comment]
I'm closing this, i think there're  more important things and probably this is too subtle change... we can always re-open. Besides it may mess up things with DZ
