### ISSUE TITLE
Scenes update

### ISSUE THREAD

**Issue by EdddieN** [EdddieN/machinon-domoticz_theme#73]
Is it possible to add custom icons to Scenes?
right now we have this?
![screen shot 2018-09-05 at 18 45 47](https://user-images.githubusercontent.com/39434245/45111093-fc5de980-b13b-11e8-9288-6558ec35837d.png)

would be nice if we could:
![screen shot 2018-09-05 at 18 45 54](https://user-images.githubusercontent.com/39434245/45111111-02ec6100-b13c-11e8-9a77-67a417099908.png)

**Comment by landaisbenj** [comment]
I thinks it may be hard.

**Comment by EdddieN** [comment]
Ok, I leave it as a feature for now, we can always close it

**Comment by EdddieN** [comment]
closing for now. We have the designs in zepling, we can always re-open if extra time.
