### ISSUE TITLE
List devices icons

### ISSUE THREAD

**Issue by EdddieN** [EdddieN/machinon-domoticz_theme#74]
change from
![screen shot 2018-09-05 at 18 48 12](https://user-images.githubusercontent.com/39434245/45111212-4d6ddd80-b13c-11e8-9da5-735034ccc9d0.png)
to
![screen shot 2018-09-05 at 18 48 05](https://user-images.githubusercontent.com/39434245/45111218-52329180-b13c-11e8-9010-ed1092f86caf.png)

**Comment by EdddieN** [comment]
It is the icon mostly, the blue and green one, the other black ones not so important but also could be done. All in zeplin

**Comment by DewGew** [comment]
Added some in #86

**Comment by EdddieN** [comment]
See attached, the icons on mine appear very close
![screen shot 2018-09-11 at 11 25 42](https://user-images.githubusercontent.com/39434245/45354551-c72b1e80-b5b5-11e8-8684-07fb269cb9e3.png)

**Comment by DewGew** [comment]
Check latest i added a icon with bigger space to the left..

**Comment by EdddieN** [comment]
yes!
