### ISSUE TITLE
Events screen

### ISSUE THREAD

**Issue by EdddieN** [EdddieN/machinon-domoticz_theme#75]
Is this possible? From
![screen shot 2018-09-05 at 18 50 29](https://user-images.githubusercontent.com/39434245/45111326-a473b280-b13c-11e8-931d-efce3e3efb76.png)
to
![screen shot 2018-09-05 at 18 50 37](https://user-images.githubusercontent.com/39434245/45111355-b190a180-b13c-11e8-9450-bb203a5ce374.png)

**Comment by landaisbenj** [comment]
It's a big feature for me. Event screen is really important even if few people use it. But it's a big part of a js code

**Comment by EdddieN** [comment]
Given that the visual changes are very small, best to close this? We don't want to break the events screen by accident :)  I leave it marked as feature request, I don' think is that critical.

**Comment by landaisbenj** [comment]
Let it open. Maybe we can just make visual change

**Comment by EdddieN** [comment]
I'm closing this, I think if we touch this screen too much we  may risk messing the logic from Blockly. too risky and changes are minor.  I think there more important areas to cover like cameras too.

**Comment by landaisbenj** [comment]
Hmm. One day, when I will have time, I try to do something with event.

**Comment by EdddieN** [comment]
Don't worry honestly, I do not think it brings much value to the user. There're other areas that will bring more value like the dash cams, important notification and events history

**Comment by landaisbenj** [comment]
See the next event editor !!! <3 just push on beta branch...

https://github.com/domoticz/domoticz/pull/2755

**Comment by landaisbenj** [comment]
![](https://user-images.githubusercontent.com/2734836/46501686-d6a52c80-c82e-11e8-8aa1-7077591eb623.png)

![](https://user-images.githubusercontent.com/2734836/46904703-47181180-cef1-11e8-9b5d-fa7f25126457.png)
