### ISSUE TITLE
Tiles colour coding - WIP

### ISSUE THREAD

**Issue by EdddieN** [EdddieN/machinon-domoticz_theme#76]
This is work in progress, so far the tiles can indicate, device is:
Online
Offline
Alarm threshold, like to high CO2
Device blocked so it cannot be activated

Anything else? I need to update the design to indicate these status on the tiles. So far we can play with the tiles being faded out for online / offline

then we have a thin line colour around the tile to indicate properties

I think we could also indicate alarm things by changing the colour of the text value, even colour + bold... just a few ideas

**Comment by EdddieN** [comment]
Example of red text
![screen shot 2018-09-05 at 18 56 18](https://user-images.githubusercontent.com/39434245/45111657-6a56e080-b13d-11e8-96c4-ebc4b346c1b8.png)

**Comment by EdddieN** [comment]
https://github.com/EdddieN/machinon-domoticz_theme/issues/113

**Comment by EdddieN** [comment]
I think I just merge this:

Is this correct?
Green = locked
Red = offline
Yellow = warning level
Black = ? locked?

For now I just need confirmation what each means.

**Comment by DewGew** [comment]
Black = normal

**Comment by EdddieN** [comment]
Ok, so for now Tiles border colour reflect the status of the device itself.

Regarding the border lines, I would suggest the following:

Deep blue = locked
Black / blue (as it i now) = as it is
Red = offline

Then I have a few suggestions:
1.- Battery, should not this be an icon on the tile that only appears when battery low?
2.- Last seen, should read 3h ago, 20 days ago... rather than a date?

The reason for using the border colours as little as possible is because visually are very powerful and probably we should use them for things that are really important. For example offline = very important but a low battery? it is a warning, not a critical thing, right?

What do you think? These are just suggestions

**Comment by landaisbenj** [comment]
You're right. Maybe we can do this before title with animation only with css...

2 must be great a think. Date are visible on log page...

**Comment by landaisbenj** [comment]
With this: 

```
div.item.statusTimeout #name:before {
	 content:'';
	 display: inline-block;
	 width: 32px;
	 height: 16px;
	 background-image: url('../images/battery.png');
	 background-repeat: no-repeat;

}
```

We can do this;

![image](https://user-images.githubusercontent.com/32144431/46083455-ce4f5080-c1a1-11e8-93ea-2453cea2f4b5.png)

**Comment by EdddieN** [comment]
Yes, that is the idea. I was hoping in a place that would not take space from title text or inteference too much with custom input. Like below:
![screenshot 2018-09-26 at 17 11 31](https://user-images.githubusercontent.com/39434245/46093540-80414980-c1af-11e8-8357-c6ca96123e45.png)

Also, if we can remove date by: See 15 minutes ago, also frees up some space

**Comment by DewGew** [comment]
Something like this maybe?

![lowbattery](https://user-images.githubusercontent.com/28799807/46339142-50bc9200-c632-11e8-8f8b-0f90b18d0713.gif)

**Comment by DewGew** [comment]
And protected like this:

![protected](https://user-images.githubusercontent.com/28799807/46339871-32f02c80-c634-11e8-80ae-ccbb00313821.png)

**Comment by EdddieN** [comment]
I really like this one! https://github.com/EdddieN/machinon-domoticz_theme/issues/76#issuecomment-426204784 
However, the icon is fighting with the text a bit. Is there any other "easy" place to put it? For example before the "Last Seen...." since it is less important? Also we should look into removing text from there, is too long to read

I really like the fading effect here for the battery: https://github.com/EdddieN/machinon-domoticz_theme/issues/76#issuecomment-426200936

**Comment by DewGew** [comment]
Sure IF we dont want it

**Comment by EdddieN** [comment]
After using it for a while, I thin the red is really good for offline, but the yellow with the battery icon not so much. Any chance of removing the yellow?

Or if we want to get very fancy, letting the user select what border they want for what?

**Comment by DewGew** [comment]
> yes i'm on this on last pull. i do this but i need your review : [ddde838](https://github.com/EdddieN/machinon-domoticz_theme/commit/ddde8382bf427d3d1044ab29a62d8e99ae8215de)

Not working in Temperatures and weather..

**Comment by DewGew** [comment]
@landaisbenj  Are you using old files.. colors is not same in as in beta??

**Comment by landaisbenj** [comment]
> @landaisbenj Are you using old files.. colors is not same in as in beta??

No i don't think. I just modify custom.css in beta branch in github site...

**Comment by landaisbenj** [comment]
> > yes i'm on this on last pull. i do this but i need your review : [ddde838](https://github.com/EdddieN/machinon-domoticz_theme/commit/ddde8382bf427d3d1044ab29a62d8e99ae8215de)
> 
> Not working in Temperatures and weather.. and dashboard

oO there not have the same dom oOoOoO. It's really funcking feet coding. Have basicly do flex for span4 class... So i must do all for div.item. I look at that.

**Comment by EdddieN** [comment]
feed coding? :D never heard it before, I like it! haha!

**Comment by landaisbenj** [comment]
Lol french expression xD

**Comment by EdddieN** [comment]
it works fine for me, thin fixed on the last update. Closing.
