### ISSUE TITLE
Type Search

### ISSUE THREAD

**Issue by EdddieN** [EdddieN/machinon-domoticz_theme#77]
is this possible?
![screen shot 2018-09-05 at 21 56 25](https://user-images.githubusercontent.com/39434245/45120678-be21f380-b156-11e8-8935-5ad2ad859b13.png)

when nothing typed, the text is lighter, almost faded. When typing then it is good at is it. 
See original design as reference:
![screen shot 2018-09-05 at 21 58 36](https://user-images.githubusercontent.com/39434245/45120728-e1e53980-b156-11e8-930e-411c2b8f0291.png)

Not critical, just asking.

**Comment by DewGew** [comment]
Changes in #78
