### ISSUE TITLE
No log icon for temperatures

### ISSUE THREAD

**Issue by sweetpants** [EdddieN/machinon-domoticz_theme#92]
Temperature devices log still has to be entered via menu instead of log icon like in other tab-screens

**Comment by EdddieN** [comment]
They are there, make sure to really refresh / clean cache and app cache. I had the same issue before
![screen shot 2018-09-11 at 21 01 07](https://user-images.githubusercontent.com/39434245/45384483-1ac55880-b606-11e8-9c63-278f7581fa58.png)

**Comment by EdddieN** [comment]
Feel free to close when you get it (if you get it)
