### ISSUE TITLE
Update checker selection breaks theme

### ISSUE THREAD

**Issue by EdddieN** [EdddieN/machinon-domoticz_theme#96]
When selecting "Check for updates" it breaks part of the theme.

Disabling them fixes it again

**Comment by EdddieN** [comment]
See attached, this is what happens @DewGew 
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/39434245/45441878-46a11680-b6b8-11e8-8864-30b97658e861.gif)

**Comment by DewGew** [comment]
There is a typo fault in funktions.js 
Find this :  console.log(themeNmae + " - Loading .......
Change the ”themeNmae” to ”themeName” then it Will be ok. (Im not at a computer today) :)

**Comment by EdddieN** [comment]
Brilliant, I updated the file now and it works ok. Just missing the version number, I'll open a visual bug for that
